// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: agent.proto

package hannah

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResidentType int32

const (
	ResidentType_RESIDENT_TYPE_UNSPECIFIED ResidentType = 0
	ResidentType_ROOMIE                    ResidentType = 1
	ResidentType_GUEST                     ResidentType = 2
	ResidentType_PET                       ResidentType = 3
)

// Enum value maps for ResidentType.
var (
	ResidentType_name = map[int32]string{
		0: "RESIDENT_TYPE_UNSPECIFIED",
		1: "ROOMIE",
		2: "GUEST",
		3: "PET",
	}
	ResidentType_value = map[string]int32{
		"RESIDENT_TYPE_UNSPECIFIED": 0,
		"ROOMIE":                    1,
		"GUEST":                     2,
		"PET":                       3,
	}
)

func (x ResidentType) Enum() *ResidentType {
	p := new(ResidentType)
	*p = x
	return p
}

func (x ResidentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResidentType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (ResidentType) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x ResidentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResidentType.Descriptor instead.
func (ResidentType) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

// Sent by the HannahAgent ioBroker adapter over the AgentConnect stream.
type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_StateUpdate
	//	*AgentMessage_ResidentUpdate
	//	*AgentMessage_TextCommand
	//	*AgentMessage_SatelliteControl
	//	*AgentMessage_SendSnapshot
	//	*AgentMessage_SendResidents
	//	*AgentMessage_AskResident
	//	*AgentMessage_SendRooms
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetStateUpdate() *AgentStateUpdate {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_StateUpdate); ok {
			return x.StateUpdate
		}
	}
	return nil
}

func (x *AgentMessage) GetResidentUpdate() *AgentResident {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_ResidentUpdate); ok {
			return x.ResidentUpdate
		}
	}
	return nil
}

func (x *AgentMessage) GetTextCommand() *AgentTextCommand {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_TextCommand); ok {
			return x.TextCommand
		}
	}
	return nil
}

func (x *AgentMessage) GetSatelliteControl() *AgentSatelliteControl {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_SatelliteControl); ok {
			return x.SatelliteControl
		}
	}
	return nil
}

func (x *AgentMessage) GetSendSnapshot() *AgentDeviceSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_SendSnapshot); ok {
			return x.SendSnapshot
		}
	}
	return nil
}

func (x *AgentMessage) GetSendResidents() *AgentResidentSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_SendResidents); ok {
			return x.SendResidents
		}
	}
	return nil
}

func (x *AgentMessage) GetAskResident() *AgentAskResident {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_AskResident); ok {
			return x.AskResident
		}
	}
	return nil
}

func (x *AgentMessage) GetSendRooms() *AgentRoomSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_SendRooms); ok {
			return x.SendRooms
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_StateUpdate struct {
	StateUpdate *AgentStateUpdate `protobuf:"bytes,1,opt,name=state_update,json=stateUpdate,proto3,oneof"` // any ioBroker state changed
}

type AgentMessage_ResidentUpdate struct {
	ResidentUpdate *AgentResident `protobuf:"bytes,2,opt,name=resident_update,json=residentUpdate,proto3,oneof"` // residents adapter presence changed
}

type AgentMessage_TextCommand struct {
	TextCommand *AgentTextCommand `protobuf:"bytes,3,opt,name=text_command,json=textCommand,proto3,oneof"` // text command state changed
}

type AgentMessage_SatelliteControl struct {
	SatelliteControl *AgentSatelliteControl `protobuf:"bytes,4,opt,name=satellite_control,json=satelliteControl,proto3,oneof"` // satellite control command
}

type AgentMessage_SendSnapshot struct {
	SendSnapshot *AgentDeviceSnapshot `protobuf:"bytes,5,opt,name=send_snapshot,json=sendSnapshot,proto3,oneof"` // initial snapshot with all states
}

type AgentMessage_SendResidents struct {
	SendResidents *AgentResidentSnapshot `protobuf:"bytes,6,opt,name=send_residents,json=sendResidents,proto3,oneof"` // initial snapshot with all residents
}

type AgentMessage_AskResident struct {
	AskResident *AgentAskResident `protobuf:"bytes,7,opt,name=ask_resident,json=askResident,proto3,oneof"` // ask Resident via Hannah
}

type AgentMessage_SendRooms struct {
	SendRooms *AgentRoomSnapshot `protobuf:"bytes,8,opt,name=send_rooms,json=sendRooms,proto3,oneof"` // full room catalog, independent of devices
}

func (*AgentMessage_StateUpdate) isAgentMessage_Payload() {}

func (*AgentMessage_ResidentUpdate) isAgentMessage_Payload() {}

func (*AgentMessage_TextCommand) isAgentMessage_Payload() {}

func (*AgentMessage_SatelliteControl) isAgentMessage_Payload() {}

func (*AgentMessage_SendSnapshot) isAgentMessage_Payload() {}

func (*AgentMessage_SendResidents) isAgentMessage_Payload() {}

func (*AgentMessage_AskResident) isAgentMessage_Payload() {}

func (*AgentMessage_SendRooms) isAgentMessage_Payload() {}

// Adapter instructs Hannah to control satellites in a room or a specific satellite.
// room: room_id (enum ID segment) or "all" for all rooms.
// device_id: if non-empty, only the named satellite is targeted (volume/mute only);
//
//	room is still required (used for room-scoped commands and as fallback).
type AgentSatelliteControl struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Room     string                 `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	DeviceId string                 `protobuf:"bytes,7,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // optional: target a specific satellite instead of the whole room
	// Types that are valid to be assigned to Control:
	//
	//	*AgentSatelliteControl_Dnd
	//	*AgentSatelliteControl_Mute
	//	*AgentSatelliteControl_Volume
	//	*AgentSatelliteControl_Announcement
	//	*AgentSatelliteControl_AnnouncementSsml
	//	*AgentSatelliteControl_AnnouncementRephrase
	Control       isAgentSatelliteControl_Control `protobuf_oneof:"control"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSatelliteControl) Reset() {
	*x = AgentSatelliteControl{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSatelliteControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSatelliteControl) ProtoMessage() {}

func (x *AgentSatelliteControl) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSatelliteControl.ProtoReflect.Descriptor instead.
func (*AgentSatelliteControl) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentSatelliteControl) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *AgentSatelliteControl) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AgentSatelliteControl) GetControl() isAgentSatelliteControl_Control {
	if x != nil {
		return x.Control
	}
	return nil
}

func (x *AgentSatelliteControl) GetDnd() bool {
	if x != nil {
		if x, ok := x.Control.(*AgentSatelliteControl_Dnd); ok {
			return x.Dnd
		}
	}
	return false
}

func (x *AgentSatelliteControl) GetMute() bool {
	if x != nil {
		if x, ok := x.Control.(*AgentSatelliteControl_Mute); ok {
			return x.Mute
		}
	}
	return false
}

func (x *AgentSatelliteControl) GetVolume() int32 {
	if x != nil {
		if x, ok := x.Control.(*AgentSatelliteControl_Volume); ok {
			return x.Volume
		}
	}
	return 0
}

func (x *AgentSatelliteControl) GetAnnouncement() string {
	if x != nil {
		if x, ok := x.Control.(*AgentSatelliteControl_Announcement); ok {
			return x.Announcement
		}
	}
	return ""
}

func (x *AgentSatelliteControl) GetAnnouncementSsml() string {
	if x != nil {
		if x, ok := x.Control.(*AgentSatelliteControl_AnnouncementSsml); ok {
			return x.AnnouncementSsml
		}
	}
	return ""
}

func (x *AgentSatelliteControl) GetAnnouncementRephrase() string {
	if x != nil {
		if x, ok := x.Control.(*AgentSatelliteControl_AnnouncementRephrase); ok {
			return x.AnnouncementRephrase
		}
	}
	return ""
}

type isAgentSatelliteControl_Control interface {
	isAgentSatelliteControl_Control()
}

type AgentSatelliteControl_Dnd struct {
	Dnd bool `protobuf:"varint,2,opt,name=dnd,proto3,oneof"` // set do-not-disturb
}

type AgentSatelliteControl_Mute struct {
	Mute bool `protobuf:"varint,3,opt,name=mute,proto3,oneof"` // mute/unmute microphone
}

type AgentSatelliteControl_Volume struct {
	Volume int32 `protobuf:"varint,4,opt,name=volume,proto3,oneof"` // set volume (0–100)
}

type AgentSatelliteControl_Announcement struct {
	Announcement string `protobuf:"bytes,5,opt,name=announcement,proto3,oneof"` // speak plain-text announcement (verbatim)
}

type AgentSatelliteControl_AnnouncementSsml struct {
	AnnouncementSsml string `protobuf:"bytes,6,opt,name=announcement_ssml,json=announcementSsml,proto3,oneof"` // speak SSML announcement
}

type AgentSatelliteControl_AnnouncementRephrase struct {
	AnnouncementRephrase string `protobuf:"bytes,8,opt,name=announcement_rephrase,json=announcementRephrase,proto3,oneof"` // speak announcement, text rephrased by LLM first
}

func (*AgentSatelliteControl_Dnd) isAgentSatelliteControl_Control() {}

func (*AgentSatelliteControl_Mute) isAgentSatelliteControl_Control() {}

func (*AgentSatelliteControl_Volume) isAgentSatelliteControl_Control() {}

func (*AgentSatelliteControl_Announcement) isAgentSatelliteControl_Control() {}

func (*AgentSatelliteControl_AnnouncementSsml) isAgentSatelliteControl_Control() {}

func (*AgentSatelliteControl_AnnouncementRephrase) isAgentSatelliteControl_Control() {}

// An ioBroker state change event. ack=true means the device confirmed the value
// (as opposed to ack=false which is the "desired" value). Hannah uses this to
// verify that a SetState command was executed successfully.
type AgentStateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateId       string                 `protobuf:"bytes,1,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"` // full ioBroker state ID, e.g. "javascript.0.virtualDevice.Licht.EG.Wohnzimmer.DeckeSeite.on"
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`                    // JSON-encoded value: "true", "42", "\"text\""
	Ack           bool                   `protobuf:"varint,3,opt,name=ack,proto3" json:"ack,omitempty"`                       // true = confirmed by device
	Ts            int64                  `protobuf:"varint,4,opt,name=ts,proto3" json:"ts,omitempty"`                         // Unix timestamp in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStateUpdate) Reset() {
	*x = AgentStateUpdate{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStateUpdate) ProtoMessage() {}

func (x *AgentStateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStateUpdate.ProtoReflect.Descriptor instead.
func (*AgentStateUpdate) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *AgentStateUpdate) GetStateId() string {
	if x != nil {
		return x.StateId
	}
	return ""
}

func (x *AgentStateUpdate) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AgentStateUpdate) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

func (x *AgentStateUpdate) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

// The text-command state in ioBroker changed — treat as a SubmitText call.
type AgentTextCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentTextCommand) Reset() {
	*x = AgentTextCommand{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTextCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTextCommand) ProtoMessage() {}

func (x *AgentTextCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTextCommand.ProtoReflect.Descriptor instead.
func (*AgentTextCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentTextCommand) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Sent by Hannah Core over the AgentConnect stream.
type AgentCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*AgentCommand_SetState
	//	*AgentCommand_WatchMore
	//	*AgentCommand_SetResident
	//	*AgentCommand_SatelliteUpdate
	//	*AgentCommand_TextAnswer
	//	*AgentCommand_FirmwareEvent
	//	*AgentCommand_BleUpdate
	//	*AgentCommand_SensorUpdate
	//	*AgentCommand_ResidentAnswered
	//	*AgentCommand_SatelliteDeleted
	//	*AgentCommand_SetResidentMood
	Command       isAgentCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCommand) Reset() {
	*x = AgentCommand{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommand) ProtoMessage() {}

func (x *AgentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommand.ProtoReflect.Descriptor instead.
func (*AgentCommand) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AgentCommand) GetCommand() isAgentCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *AgentCommand) GetSetState() *AgentSetState {
	if x != nil {
		if x, ok := x.Command.(*AgentCommand_SetState); ok {
			return x.SetState
		}
	}
	return nil
}

func (x *AgentCommand) GetWatchMore() *AgentWatchMore {
	if x != nil {
		if x, ok := x.Command.(*AgentCommand_WatchMore); ok {
			return x.WatchMore
		}
	}
	return nil
}

func (x *AgentCommand) GetSetResident() *AgentSetResident {
	if x != nil {
		if x, ok := x.Command.(*AgentCommand_SetResident); ok {
			return x.SetResident
		}
	}
	return nil
}

func (x *AgentCommand) GetSatelliteUpdate() *AgentSatelliteUpdate {
	if x != nil {
		if x, ok := x.Command.(*AgentCommand_SatelliteUpdate); ok {
			return x.SatelliteUpdate
		}
	}
	return nil
}

func (x *AgentCommand) GetTextAnswer() *AgentTextAnswer {
	if x != nil {
		if x, ok := x.Command.(*AgentCommand_TextAnswer); ok {
			return x.TextAnswer
		}
	}
	return nil
}

func (x *AgentCommand) GetFirmwareEvent() *AgentFirmwareEvent {
	if x != nil {
		if x, ok := x.Command.(*AgentCommand_FirmwareEvent); ok {
			return x.FirmwareEvent
		}
	}
	return nil
}

func (x *AgentCommand) GetBleUpdate() *AgentBleUpdate {
	if x != nil {
		if x, ok := x.Command.(*AgentCommand_BleUpdate); ok {
			return x.BleUpdate
		}
	}
	return nil
}

func (x *AgentCommand) GetSensorUpdate() *AgentSensorUpdate {
	if x != nil {
		if x, ok := x.Command.(*AgentCommand_SensorUpdate); ok {
			return x.SensorUpdate
		}
	}
	return nil
}

func (x *AgentCommand) GetResidentAnswered() *AgentResidentAnswered {
	if x != nil {
		if x, ok := x.Command.(*AgentCommand_ResidentAnswered); ok {
			return x.ResidentAnswered
		}
	}
	return nil
}

func (x *AgentCommand) GetSatelliteDeleted() *AgentSatelliteDeleted {
	if x != nil {
		if x, ok := x.Command.(*AgentCommand_SatelliteDeleted); ok {
			return x.SatelliteDeleted
		}
	}
	return nil
}

func (x *AgentCommand) GetSetResidentMood() *AgentSetResidentMood {
	if x != nil {
		if x, ok := x.Command.(*AgentCommand_SetResidentMood); ok {
			return x.SetResidentMood
		}
	}
	return nil
}

type isAgentCommand_Command interface {
	isAgentCommand_Command()
}

type AgentCommand_SetState struct {
	SetState *AgentSetState `protobuf:"bytes,1,opt,name=set_state,json=setState,proto3,oneof"` // Hannah wants to control an ioBroker device
}

type AgentCommand_WatchMore struct {
	WatchMore *AgentWatchMore `protobuf:"bytes,2,opt,name=watch_more,json=watchMore,proto3,oneof"` // Hannah needs additional states streamed
}

type AgentCommand_SetResident struct {
	SetResident *AgentSetResident `protobuf:"bytes,3,opt,name=set_resident,json=setResident,proto3,oneof"` // Hannah wants to set a resident's presence state
}

type AgentCommand_SatelliteUpdate struct {
	SatelliteUpdate *AgentSatelliteUpdate `protobuf:"bytes,4,opt,name=satellite_update,json=satelliteUpdate,proto3,oneof"` // a satellite registered or disconnected
}

type AgentCommand_TextAnswer struct {
	TextAnswer *AgentTextAnswer `protobuf:"bytes,5,opt,name=text_answer,json=textAnswer,proto3,oneof"` // Hannah's answer to a text command
}

type AgentCommand_FirmwareEvent struct {
	FirmwareEvent *AgentFirmwareEvent `protobuf:"bytes,6,opt,name=firmware_event,json=firmwareEvent,proto3,oneof"` // satellite firmware version update
}

type AgentCommand_BleUpdate struct {
	BleUpdate *AgentBleUpdate `protobuf:"bytes,7,opt,name=ble_update,json=bleUpdate,proto3,oneof"` // BLE tag location changed
}

type AgentCommand_SensorUpdate struct {
	SensorUpdate *AgentSensorUpdate `protobuf:"bytes,8,opt,name=sensor_update,json=sensorUpdate,proto3,oneof"` // satellite sensor reading
}

type AgentCommand_ResidentAnswered struct {
	ResidentAnswered *AgentResidentAnswered `protobuf:"bytes,9,opt,name=resident_answered,json=residentAnswered,proto3,oneof"` // answer to an ask_resident request
}

type AgentCommand_SatelliteDeleted struct {
	SatelliteDeleted *AgentSatelliteDeleted `protobuf:"bytes,10,opt,name=satellite_deleted,json=satelliteDeleted,proto3,oneof"` // Hannah Core deleted a satellite — adapter must remove its object tree
}

type AgentCommand_SetResidentMood struct {
	SetResidentMood *AgentSetResidentMood `protobuf:"bytes,11,opt,name=set_resident_mood,json=setResidentMood,proto3,oneof"` // Hannah wants to set a resident's mood, independent of presence
}

func (*AgentCommand_SetState) isAgentCommand_Command() {}

func (*AgentCommand_WatchMore) isAgentCommand_Command() {}

func (*AgentCommand_SetResident) isAgentCommand_Command() {}

func (*AgentCommand_SatelliteUpdate) isAgentCommand_Command() {}

func (*AgentCommand_TextAnswer) isAgentCommand_Command() {}

func (*AgentCommand_FirmwareEvent) isAgentCommand_Command() {}

func (*AgentCommand_BleUpdate) isAgentCommand_Command() {}

func (*AgentCommand_SensorUpdate) isAgentCommand_Command() {}

func (*AgentCommand_ResidentAnswered) isAgentCommand_Command() {}

func (*AgentCommand_SatelliteDeleted) isAgentCommand_Command() {}

func (*AgentCommand_SetResidentMood) isAgentCommand_Command() {}

type AgentFirmwareEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Device          string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	UpdateAvailable bool                   `protobuf:"varint,3,opt,name=update_available,json=updateAvailable,proto3" json:"update_available,omitempty"` // true = newer version pending, false = current version report
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentFirmwareEvent) Reset() {
	*x = AgentFirmwareEvent{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentFirmwareEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentFirmwareEvent) ProtoMessage() {}

func (x *AgentFirmwareEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentFirmwareEvent.ProtoReflect.Descriptor instead.
func (*AgentFirmwareEvent) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AgentFirmwareEvent) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *AgentFirmwareEvent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentFirmwareEvent) GetUpdateAvailable() bool {
	if x != nil {
		return x.UpdateAvailable
	}
	return false
}

// Hannah instructs the adapter to set an ioBroker state.
// The adapter calls setForeignState(); the resulting ack=true AgentStateUpdate
// confirms execution back to Hannah.
type AgentSetState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateId       string                 `protobuf:"bytes,1,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"` // ioBroker state ID to write
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`                    // JSON-encoded value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSetState) Reset() {
	*x = AgentSetState{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSetState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSetState) ProtoMessage() {}

func (x *AgentSetState) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSetState.ProtoReflect.Descriptor instead.
func (*AgentSetState) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *AgentSetState) GetStateId() string {
	if x != nil {
		return x.StateId
	}
	return ""
}

func (x *AgentSetState) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Hannah requests additional state IDs to be included in the AgentStateUpdate stream.
// Used by the trigger engine at runtime when triggers reference arbitrary state IDs
// (e.g. unless.state: "0_userdata.0.feeded") that aren't covered by enum discovery.
type AgentWatchMore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateIds      []string               `protobuf:"bytes,1,rep,name=state_ids,json=stateIds,proto3" json:"state_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentWatchMore) Reset() {
	*x = AgentWatchMore{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentWatchMore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentWatchMore) ProtoMessage() {}

func (x *AgentWatchMore) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentWatchMore.ProtoReflect.Descriptor instead.
func (*AgentWatchMore) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *AgentWatchMore) GetStateIds() []string {
	if x != nil {
		return x.StateIds
	}
	return nil
}

// Hannah instructs the adapter to set a resident's presence state in the residents adapter.
// type determines whether the target path is .roomie./.guest./.pet.
type AgentSetResident struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResidentId    string                 `protobuf:"bytes,1,opt,name=resident_id,json=residentId,proto3" json:"resident_id,omitempty"`           // e.g. "leonie", "hannah"
	PresenceState int32                  `protobuf:"varint,2,opt,name=presence_state,json=presenceState,proto3" json:"presence_state,omitempty"` // residents adapter presence value (0=absent, 1=home, …)
	Type          ResidentType           `protobuf:"varint,3,opt,name=type,proto3,enum=hannah.ResidentType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSetResident) Reset() {
	*x = AgentSetResident{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSetResident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSetResident) ProtoMessage() {}

func (x *AgentSetResident) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSetResident.ProtoReflect.Descriptor instead.
func (*AgentSetResident) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *AgentSetResident) GetResidentId() string {
	if x != nil {
		return x.ResidentId
	}
	return ""
}

func (x *AgentSetResident) GetPresenceState() int32 {
	if x != nil {
		return x.PresenceState
	}
	return 0
}

func (x *AgentSetResident) GetType() ResidentType {
	if x != nil {
		return x.Type
	}
	return ResidentType_RESIDENT_TYPE_UNSPECIFIED
}

// Hannah instructs the adapter to set a resident's mood — separate command from
// AgentSetResident so it can fire independent of any presence change (e.g. when a
// Hannah User's linked mood changes without an arrival/departure).
type AgentSetResidentMood struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResidentId    string                 `protobuf:"bytes,1,opt,name=resident_id,json=residentId,proto3" json:"resident_id,omitempty"` // e.g. "leonie", "hannah"
	Mood          int32                  `protobuf:"varint,2,opt,name=mood,proto3" json:"mood,omitempty"`
	Type          ResidentType           `protobuf:"varint,3,opt,name=type,proto3,enum=hannah.ResidentType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSetResidentMood) Reset() {
	*x = AgentSetResidentMood{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSetResidentMood) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSetResidentMood) ProtoMessage() {}

func (x *AgentSetResidentMood) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSetResidentMood.ProtoReflect.Descriptor instead.
func (*AgentSetResidentMood) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *AgentSetResidentMood) GetResidentId() string {
	if x != nil {
		return x.ResidentId
	}
	return ""
}

func (x *AgentSetResidentMood) GetMood() int32 {
	if x != nil {
		return x.Mood
	}
	return 0
}

func (x *AgentSetResidentMood) GetType() ResidentType {
	if x != nil {
		return x.Type
	}
	return ResidentType_RESIDENT_TYPE_UNSPECIFIED
}

// Hannah notifies the adapter that a satellite registered or disconnected,
// or that a satellite's volume or mute state changed.
// The adapter updates hannah.<instance>.satellites.rooms.<room_id>.* states accordingly.
type AgentSatelliteUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`          // satellite device_id (== eFuse MAC since v0.34); adapter uses as ioBroker object-ID
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`                                  // room_id: stable enum ID segment (e.g. "wohnzimmer"); adapter uses as ioBroker path segment
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`                            // UDP address (empty if not applicable)
	Online        bool                   `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`                             // true = registered/online, false = gone/offline
	Volume        *int32                 `protobuf:"varint,5,opt,name=volume,proto3,oneof" json:"volume,omitempty"`                       // current volume level (0–100); absent = no change
	Mute          *bool                  `protobuf:"varint,6,opt,name=mute,proto3,oneof" json:"mute,omitempty"`                           // current mute state; absent = no change
	DisplayName   string                 `protobuf:"bytes,8,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // human-readable name from Core DB (empty = fall back to device_id)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSatelliteUpdate) Reset() {
	*x = AgentSatelliteUpdate{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSatelliteUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSatelliteUpdate) ProtoMessage() {}

func (x *AgentSatelliteUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSatelliteUpdate.ProtoReflect.Descriptor instead.
func (*AgentSatelliteUpdate) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *AgentSatelliteUpdate) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AgentSatelliteUpdate) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *AgentSatelliteUpdate) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AgentSatelliteUpdate) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *AgentSatelliteUpdate) GetVolume() int32 {
	if x != nil && x.Volume != nil {
		return *x.Volume
	}
	return 0
}

func (x *AgentSatelliteUpdate) GetMute() bool {
	if x != nil && x.Mute != nil {
		return *x.Mute
	}
	return false
}

func (x *AgentSatelliteUpdate) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

// Hannah Core deleted a satellite (RoomManager.delete_satellite()) — the adapter
// must remove the satellite's full object tree (and its sensor tree), mirroring
// the room cleanup AgentSatelliteUpdate already does for online/offline changes.
type AgentSatelliteDeleted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // satellite device_id being deleted
	Room          string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`                         // room_id the satellite was assigned to, for room-container cleanup
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSatelliteDeleted) Reset() {
	*x = AgentSatelliteDeleted{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSatelliteDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSatelliteDeleted) ProtoMessage() {}

func (x *AgentSatelliteDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSatelliteDeleted.ProtoReflect.Descriptor instead.
func (*AgentSatelliteDeleted) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *AgentSatelliteDeleted) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AgentSatelliteDeleted) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

// Hannah sends the answer to a text command back to the adapter.
// The adapter sets hannah.<instance>.textAnswer accordingly.
type AgentTextAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`     // plain-text answer
	Intent        string                 `protobuf:"bytes,2,opt,name=intent,proto3" json:"intent,omitempty"` // detected intent name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentTextAnswer) Reset() {
	*x = AgentTextAnswer{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTextAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTextAnswer) ProtoMessage() {}

func (x *AgentTextAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTextAnswer.ProtoReflect.Descriptor instead.
func (*AgentTextAnswer) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *AgentTextAnswer) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AgentTextAnswer) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

// A notification from the ioBroker adapter.
// direct=true: skip LLM, play text unchanged (severity ignored).
// direct=false: LLM reformulates text; severity controls tone ("alert"|"notify"|"info").
type AgentNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Direct        bool                   `protobuf:"varint,2,opt,name=direct,proto3" json:"direct,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"` // "alert" | "notify" | "info" — only used when direct=false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentNotification) Reset() {
	*x = AgentNotification{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentNotification) ProtoMessage() {}

func (x *AgentNotification) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentNotification.ProtoReflect.Descriptor instead.
func (*AgentNotification) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *AgentNotification) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *AgentNotification) GetDirect() bool {
	if x != nil {
		return x.Direct
	}
	return false
}

func (x *AgentNotification) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type AgentStateValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Ack           bool                   `protobuf:"varint,2,opt,name=ack,proto3" json:"ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentStateValue) Reset() {
	*x = AgentStateValue{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentStateValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentStateValue) ProtoMessage() {}

func (x *AgentStateValue) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentStateValue.ProtoReflect.Descriptor instead.
func (*AgentStateValue) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *AgentStateValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AgentStateValue) GetAck() bool {
	if x != nil {
		return x.Ack
	}
	return false
}

// A device from the ioBroker adapter
type AgentDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateId       string                 `protobuf:"bytes,1,opt,name=state_id,json=stateId,proto3" json:"state_id,omitempty"`
	Floor         string                 `protobuf:"bytes,2,opt,name=floor,proto3" json:"floor,omitempty"`
	Room          string                 `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"` // room_id: stable enum ID segment, e.g. "wohnzimmer" or "living_room"
	Device        string                 `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	DeviceType    string                 `protobuf:"bytes,5,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	Functions     []string               `protobuf:"bytes,6,rep,name=functions,proto3" json:"functions,omitempty"`
	Value         *AgentStateValue       `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
	RoomNames     map[string]string      `protobuf:"bytes,8,rep,name=room_names,json=roomNames,proto3" json:"room_names,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // all display names from ioBroker enum, e.g. {"de": "Wohnzimmer", "en": "Living Room"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentDevice) Reset() {
	*x = AgentDevice{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDevice) ProtoMessage() {}

func (x *AgentDevice) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDevice.ProtoReflect.Descriptor instead.
func (*AgentDevice) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *AgentDevice) GetStateId() string {
	if x != nil {
		return x.StateId
	}
	return ""
}

func (x *AgentDevice) GetFloor() string {
	if x != nil {
		return x.Floor
	}
	return ""
}

func (x *AgentDevice) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *AgentDevice) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *AgentDevice) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *AgentDevice) GetFunctions() []string {
	if x != nil {
		return x.Functions
	}
	return nil
}

func (x *AgentDevice) GetValue() *AgentStateValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AgentDevice) GetRoomNames() map[string]string {
	if x != nil {
		return x.RoomNames
	}
	return nil
}

// a list with all known devices from the ioBroker adapter
type AgentDeviceSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*AgentDevice         `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentDeviceSnapshot) Reset() {
	*x = AgentDeviceSnapshot{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentDeviceSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentDeviceSnapshot) ProtoMessage() {}

func (x *AgentDeviceSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentDeviceSnapshot.ProtoReflect.Descriptor instead.
func (*AgentDeviceSnapshot) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *AgentDeviceSnapshot) GetDevices() []*AgentDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

// A room from the ioBroker adapter's enum.rooms.* catalog — independent of devices,
// so rooms without any device yet are still known to Hannah (e.g. before the first
// satellite is provisioned into a brand-new room).
type AgentRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                                                                                             // enum ID segment, e.g. "wohnzimmer"
	DisplayNames  map[string]string      `protobuf:"bytes,2,rep,name=display_names,json=displayNames,proto3" json:"display_names,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // all display names from ioBroker enum, e.g. {"de": "Wohnzimmer", "en": "Living Room"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRoom) Reset() {
	*x = AgentRoom{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRoom) ProtoMessage() {}

func (x *AgentRoom) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRoom.ProtoReflect.Descriptor instead.
func (*AgentRoom) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *AgentRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *AgentRoom) GetDisplayNames() map[string]string {
	if x != nil {
		return x.DisplayNames
	}
	return nil
}

// Full room catalog from the ioBroker adapter. Sent on AgentConnect and whenever
// enum.rooms.* changes, independent of AgentDeviceSnapshot.
type AgentRoomSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*AgentRoom           `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentRoomSnapshot) Reset() {
	*x = AgentRoomSnapshot{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRoomSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRoomSnapshot) ProtoMessage() {}

func (x *AgentRoomSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRoomSnapshot.ProtoReflect.Descriptor instead.
func (*AgentRoomSnapshot) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *AgentRoomSnapshot) GetRooms() []*AgentRoom {
	if x != nil {
		return x.Rooms
	}
	return nil
}

// A resident from the ioBroker adapter
type AgentResident struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomieId      string                 `protobuf:"bytes,1,opt,name=roomie_id,json=roomieId,proto3" json:"roomie_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          ResidentType           `protobuf:"varint,3,opt,name=type,proto3,enum=hannah.ResidentType" json:"type,omitempty"`
	MoodLevel     *int32                 `protobuf:"varint,4,opt,name=mood_level,json=moodLevel,proto3,oneof" json:"mood_level,omitempty"`
	PresenceState int32                  `protobuf:"varint,5,opt,name=presence_state,json=presenceState,proto3" json:"presence_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResident) Reset() {
	*x = AgentResident{}
	mi := &file_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResident) ProtoMessage() {}

func (x *AgentResident) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResident.ProtoReflect.Descriptor instead.
func (*AgentResident) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{19}
}

func (x *AgentResident) GetRoomieId() string {
	if x != nil {
		return x.RoomieId
	}
	return ""
}

func (x *AgentResident) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentResident) GetType() ResidentType {
	if x != nil {
		return x.Type
	}
	return ResidentType_RESIDENT_TYPE_UNSPECIFIED
}

func (x *AgentResident) GetMoodLevel() int32 {
	if x != nil && x.MoodLevel != nil {
		return *x.MoodLevel
	}
	return 0
}

func (x *AgentResident) GetPresenceState() int32 {
	if x != nil {
		return x.PresenceState
	}
	return 0
}

// a list with all known residents
type AgentResidentSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Residents     []*AgentResident       `protobuf:"bytes,1,rep,name=residents,proto3" json:"residents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResidentSnapshot) Reset() {
	*x = AgentResidentSnapshot{}
	mi := &file_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResidentSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResidentSnapshot) ProtoMessage() {}

func (x *AgentResidentSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResidentSnapshot.ProtoReflect.Descriptor instead.
func (*AgentResidentSnapshot) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{20}
}

func (x *AgentResidentSnapshot) GetResidents() []*AgentResident {
	if x != nil {
		return x.Residents
	}
	return nil
}

type AgentAskResident struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Room          string                 `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Question      string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentAskResident) Reset() {
	*x = AgentAskResident{}
	mi := &file_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentAskResident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentAskResident) ProtoMessage() {}

func (x *AgentAskResident) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentAskResident.ProtoReflect.Descriptor instead.
func (*AgentAskResident) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{21}
}

func (x *AgentAskResident) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AgentAskResident) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *AgentAskResident) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type AgentResidentAnswered struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentResidentAnswered) Reset() {
	*x = AgentResidentAnswered{}
	mi := &file_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentResidentAnswered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentResidentAnswered) ProtoMessage() {}

func (x *AgentResidentAnswered) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentResidentAnswered.ProtoReflect.Descriptor instead.
func (*AgentResidentAnswered) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{22}
}

func (x *AgentResidentAnswered) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *AgentResidentAnswered) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

// Hannah notifies the adapter that a BLE tag's location has changed.
// The adapter creates/updates states under hannah.<instance>.ble.<label>.*.
// room and satellite are empty when the tag is no longer visible.
type AgentBleUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`         // human-readable tag name (from config, used as state path)
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`             // MAC address (lowercase, colon-separated)
	Room          string                 `protobuf:"bytes,3,opt,name=room,proto3" json:"room,omitempty"`           // room name (empty = tag not visible / stale)
	Satellite     string                 `protobuf:"bytes,4,opt,name=satellite,proto3" json:"satellite,omitempty"` // satellite device ID that last detected the tag
	Rssi          int32                  `protobuf:"varint,5,opt,name=rssi,proto3" json:"rssi,omitempty"`          // last known RSSI in dBm (0 when room is empty)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentBleUpdate) Reset() {
	*x = AgentBleUpdate{}
	mi := &file_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentBleUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentBleUpdate) ProtoMessage() {}

func (x *AgentBleUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentBleUpdate.ProtoReflect.Descriptor instead.
func (*AgentBleUpdate) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{23}
}

func (x *AgentBleUpdate) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AgentBleUpdate) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *AgentBleUpdate) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *AgentBleUpdate) GetSatellite() string {
	if x != nil {
		return x.Satellite
	}
	return ""
}

func (x *AgentBleUpdate) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

// Hannah notifies the adapter of a satellite's sensor reading.
// The adapter creates/updates states under hannah.<instance>.satellites.<device>.sensors.*.
// gas_resistance is omitted (0.0) when not available (BMP280+AHT20 hardware).
// iaq/co2_equiv/voc_equiv are omitted (0.0) when BSEC2 is not calibrated yet.
type AgentSensorUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`                               // satellite device ID
	Temperature   float32                `protobuf:"fixed32,2,opt,name=temperature,proto3" json:"temperature,omitempty"`                   // °C
	Pressure      float32                `protobuf:"fixed32,3,opt,name=pressure,proto3" json:"pressure,omitempty"`                         // hPa
	Humidity      float32                `protobuf:"fixed32,4,opt,name=humidity,proto3" json:"humidity,omitempty"`                         // % relative humidity (0 when not available)
	Iaq           float32                `protobuf:"fixed32,6,opt,name=iaq,proto3" json:"iaq,omitempty"`                                   // IAQ 0–500 (BSEC2); 0 when not calibrated
	IaqAccuracy   uint32                 `protobuf:"varint,7,opt,name=iaq_accuracy,json=iaqAccuracy,proto3" json:"iaq_accuracy,omitempty"` // 0=uncertain 1=low 2=medium 3=high
	Co2Equiv      float32                `protobuf:"fixed32,8,opt,name=co2_equiv,json=co2Equiv,proto3" json:"co2_equiv,omitempty"`         // CO₂ equivalent ppm (BSEC2); 0 when not available
	VocEquiv      float32                `protobuf:"fixed32,9,opt,name=voc_equiv,json=vocEquiv,proto3" json:"voc_equiv,omitempty"`         // breath VOC equivalent ppm (BSEC2); 0 when not available
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentSensorUpdate) Reset() {
	*x = AgentSensorUpdate{}
	mi := &file_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentSensorUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentSensorUpdate) ProtoMessage() {}

func (x *AgentSensorUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentSensorUpdate.ProtoReflect.Descriptor instead.
func (*AgentSensorUpdate) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{24}
}

func (x *AgentSensorUpdate) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *AgentSensorUpdate) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *AgentSensorUpdate) GetPressure() float32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *AgentSensorUpdate) GetHumidity() float32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *AgentSensorUpdate) GetIaq() float32 {
	if x != nil {
		return x.Iaq
	}
	return 0
}

func (x *AgentSensorUpdate) GetIaqAccuracy() uint32 {
	if x != nil {
		return x.IaqAccuracy
	}
	return 0
}

func (x *AgentSensorUpdate) GetCo2Equiv() float32 {
	if x != nil {
		return x.Co2Equiv
	}
	return 0
}

func (x *AgentSensorUpdate) GetVocEquiv() float32 {
	if x != nil {
		return x.VocEquiv
	}
	return 0
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x06hannah\"\xae\x04\n" +
	"\fAgentMessage\x12=\n" +
	"\fstate_update\x18\x01 \x01(\v2\x18.hannah.AgentStateUpdateH\x00R\vstateUpdate\x12@\n" +
	"\x0fresident_update\x18\x02 \x01(\v2\x15.hannah.AgentResidentH\x00R\x0eresidentUpdate\x12=\n" +
	"\ftext_command\x18\x03 \x01(\v2\x18.hannah.AgentTextCommandH\x00R\vtextCommand\x12L\n" +
	"\x11satellite_control\x18\x04 \x01(\v2\x1d.hannah.AgentSatelliteControlH\x00R\x10satelliteControl\x12B\n" +
	"\rsend_snapshot\x18\x05 \x01(\v2\x1b.hannah.AgentDeviceSnapshotH\x00R\fsendSnapshot\x12F\n" +
	"\x0esend_residents\x18\x06 \x01(\v2\x1d.hannah.AgentResidentSnapshotH\x00R\rsendResidents\x12=\n" +
	"\fask_resident\x18\a \x01(\v2\x18.hannah.AgentAskResidentH\x00R\vaskResident\x12:\n" +
	"\n" +
	"send_rooms\x18\b \x01(\v2\x19.hannah.AgentRoomSnapshotH\x00R\tsendRoomsB\t\n" +
	"\apayload\"\xa3\x02\n" +
	"\x15AgentSatelliteControl\x12\x12\n" +
	"\x04room\x18\x01 \x01(\tR\x04room\x12\x1b\n" +
	"\tdevice_id\x18\a \x01(\tR\bdeviceId\x12\x12\n" +
	"\x03dnd\x18\x02 \x01(\bH\x00R\x03dnd\x12\x14\n" +
	"\x04mute\x18\x03 \x01(\bH\x00R\x04mute\x12\x18\n" +
	"\x06volume\x18\x04 \x01(\x05H\x00R\x06volume\x12$\n" +
	"\fannouncement\x18\x05 \x01(\tH\x00R\fannouncement\x12-\n" +
	"\x11announcement_ssml\x18\x06 \x01(\tH\x00R\x10announcementSsml\x125\n" +
	"\x15announcement_rephrase\x18\b \x01(\tH\x00R\x14announcementRephraseB\t\n" +
	"\acontrol\"e\n" +
	"\x10AgentStateUpdate\x12\x19\n" +
	"\bstate_id\x18\x01 \x01(\tR\astateId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x10\n" +
	"\x03ack\x18\x03 \x01(\bR\x03ack\x12\x0e\n" +
	"\x02ts\x18\x04 \x01(\x03R\x02ts\"&\n" +
	"\x10AgentTextCommand\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xf6\x05\n" +
	"\fAgentCommand\x124\n" +
	"\tset_state\x18\x01 \x01(\v2\x15.hannah.AgentSetStateH\x00R\bsetState\x127\n" +
	"\n" +
	"watch_more\x18\x02 \x01(\v2\x16.hannah.AgentWatchMoreH\x00R\twatchMore\x12=\n" +
	"\fset_resident\x18\x03 \x01(\v2\x18.hannah.AgentSetResidentH\x00R\vsetResident\x12I\n" +
	"\x10satellite_update\x18\x04 \x01(\v2\x1c.hannah.AgentSatelliteUpdateH\x00R\x0fsatelliteUpdate\x12:\n" +
	"\vtext_answer\x18\x05 \x01(\v2\x17.hannah.AgentTextAnswerH\x00R\n" +
	"textAnswer\x12C\n" +
	"\x0efirmware_event\x18\x06 \x01(\v2\x1a.hannah.AgentFirmwareEventH\x00R\rfirmwareEvent\x127\n" +
	"\n" +
	"ble_update\x18\a \x01(\v2\x16.hannah.AgentBleUpdateH\x00R\tbleUpdate\x12@\n" +
	"\rsensor_update\x18\b \x01(\v2\x19.hannah.AgentSensorUpdateH\x00R\fsensorUpdate\x12L\n" +
	"\x11resident_answered\x18\t \x01(\v2\x1d.hannah.AgentResidentAnsweredH\x00R\x10residentAnswered\x12L\n" +
	"\x11satellite_deleted\x18\n" +
	" \x01(\v2\x1d.hannah.AgentSatelliteDeletedH\x00R\x10satelliteDeleted\x12J\n" +
	"\x11set_resident_mood\x18\v \x01(\v2\x1c.hannah.AgentSetResidentMoodH\x00R\x0fsetResidentMoodB\t\n" +
	"\acommand\"q\n" +
	"\x12AgentFirmwareEvent\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12)\n" +
	"\x10update_available\x18\x03 \x01(\bR\x0fupdateAvailable\"@\n" +
	"\rAgentSetState\x12\x19\n" +
	"\bstate_id\x18\x01 \x01(\tR\astateId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"-\n" +
	"\x0eAgentWatchMore\x12\x1b\n" +
	"\tstate_ids\x18\x01 \x03(\tR\bstateIds\"\x84\x01\n" +
	"\x10AgentSetResident\x12\x1f\n" +
	"\vresident_id\x18\x01 \x01(\tR\n" +
	"residentId\x12%\n" +
	"\x0epresence_state\x18\x02 \x01(\x05R\rpresenceState\x12(\n" +
	"\x04type\x18\x03 \x01(\x0e2\x14.hannah.ResidentTypeR\x04type\"u\n" +
	"\x14AgentSetResidentMood\x12\x1f\n" +
	"\vresident_id\x18\x01 \x01(\tR\n" +
	"residentId\x12\x12\n" +
	"\x04mood\x18\x02 \x01(\x05R\x04mood\x12(\n" +
	"\x04type\x18\x03 \x01(\x0e2\x14.hannah.ResidentTypeR\x04type\"\xf4\x01\n" +
	"\x14AgentSatelliteUpdate\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x16\n" +
	"\x06online\x18\x04 \x01(\bR\x06online\x12\x1b\n" +
	"\x06volume\x18\x05 \x01(\x05H\x00R\x06volume\x88\x01\x01\x12\x17\n" +
	"\x04mute\x18\x06 \x01(\bH\x01R\x04mute\x88\x01\x01\x12!\n" +
	"\fdisplay_name\x18\b \x01(\tR\vdisplayNameB\t\n" +
	"\a_volumeB\a\n" +
	"\x05_muteJ\x04\b\a\x10\bR\x06serial\"H\n" +
	"\x15AgentSatelliteDeleted\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\"=\n" +
	"\x0fAgentTextAnswer\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06intent\x18\x02 \x01(\tR\x06intent\"[\n" +
	"\x11AgentNotification\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x16\n" +
	"\x06direct\x18\x02 \x01(\bR\x06direct\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\"9\n" +
	"\x0fAgentStateValue\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x10\n" +
	"\x03ack\x18\x02 \x01(\bR\x03ack\"\xd9\x02\n" +
	"\vAgentDevice\x12\x19\n" +
	"\bstate_id\x18\x01 \x01(\tR\astateId\x12\x14\n" +
	"\x05floor\x18\x02 \x01(\tR\x05floor\x12\x12\n" +
	"\x04room\x18\x03 \x01(\tR\x04room\x12\x16\n" +
	"\x06device\x18\x04 \x01(\tR\x06device\x12\x1f\n" +
	"\vdevice_type\x18\x05 \x01(\tR\n" +
	"deviceType\x12\x1c\n" +
	"\tfunctions\x18\x06 \x03(\tR\tfunctions\x12-\n" +
	"\x05value\x18\a \x01(\v2\x17.hannah.AgentStateValueR\x05value\x12A\n" +
	"\n" +
	"room_names\x18\b \x03(\v2\".hannah.AgentDevice.RoomNamesEntryR\troomNames\x1a<\n" +
	"\x0eRoomNamesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\x13AgentDeviceSnapshot\x12-\n" +
	"\adevices\x18\x01 \x03(\v2\x13.hannah.AgentDeviceR\adevices\"\xaf\x01\n" +
	"\tAgentRoom\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12H\n" +
	"\rdisplay_names\x18\x02 \x03(\v2#.hannah.AgentRoom.DisplayNamesEntryR\fdisplayNames\x1a?\n" +
	"\x11DisplayNamesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x11AgentRoomSnapshot\x12'\n" +
	"\x05rooms\x18\x01 \x03(\v2\x11.hannah.AgentRoomR\x05rooms\"\xc4\x01\n" +
	"\rAgentResident\x12\x1b\n" +
	"\troomie_id\x18\x01 \x01(\tR\broomieId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12(\n" +
	"\x04type\x18\x03 \x01(\x0e2\x14.hannah.ResidentTypeR\x04type\x12\"\n" +
	"\n" +
	"mood_level\x18\x04 \x01(\x05H\x00R\tmoodLevel\x88\x01\x01\x12%\n" +
	"\x0epresence_state\x18\x05 \x01(\x05R\rpresenceStateB\r\n" +
	"\v_mood_level\"L\n" +
	"\x15AgentResidentSnapshot\x123\n" +
	"\tresidents\x18\x01 \x03(\v2\x15.hannah.AgentResidentR\tresidents\"i\n" +
	"\x10AgentAskResident\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\x12\x12\n" +
	"\x04room\x18\x01 \x01(\tR\x04room\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\"V\n" +
	"\x15AgentResidentAnswered\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\"~\n" +
	"\x0eAgentBleUpdate\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\x12\x12\n" +
	"\x04room\x18\x03 \x01(\tR\x04room\x12\x1c\n" +
	"\tsatellite\x18\x04 \x01(\tR\tsatellite\x12\x12\n" +
	"\x04rssi\x18\x05 \x01(\x05R\x04rssi\"\x8a\x02\n" +
	"\x11AgentSensorUpdate\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x02R\vtemperature\x12\x1a\n" +
	"\bpressure\x18\x03 \x01(\x02R\bpressure\x12\x1a\n" +
	"\bhumidity\x18\x04 \x01(\x02R\bhumidity\x12\x10\n" +
	"\x03iaq\x18\x06 \x01(\x02R\x03iaq\x12!\n" +
	"\fiaq_accuracy\x18\a \x01(\rR\viaqAccuracy\x12\x1b\n" +
	"\tco2_equiv\x18\b \x01(\x02R\bco2Equiv\x12\x1b\n" +
	"\tvoc_equiv\x18\t \x01(\x02R\bvocEquivJ\x04\b\x05\x10\x06R\x0egas_resistance*M\n" +
	"\fResidentType\x12\x1d\n" +
	"\x19RESIDENT_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06ROOMIE\x10\x01\x12\t\n" +
	"\x05GUEST\x10\x02\x12\a\n" +
	"\x03PET\x10\x03B=Z;dev.kernstock.net/gessinger/voice/hannah/proxy/proto/hannahb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_agent_proto_goTypes = []any{
	(ResidentType)(0),             // 0: hannah.ResidentType
	(*AgentMessage)(nil),          // 1: hannah.AgentMessage
	(*AgentSatelliteControl)(nil), // 2: hannah.AgentSatelliteControl
	(*AgentStateUpdate)(nil),      // 3: hannah.AgentStateUpdate
	(*AgentTextCommand)(nil),      // 4: hannah.AgentTextCommand
	(*AgentCommand)(nil),          // 5: hannah.AgentCommand
	(*AgentFirmwareEvent)(nil),    // 6: hannah.AgentFirmwareEvent
	(*AgentSetState)(nil),         // 7: hannah.AgentSetState
	(*AgentWatchMore)(nil),        // 8: hannah.AgentWatchMore
	(*AgentSetResident)(nil),      // 9: hannah.AgentSetResident
	(*AgentSetResidentMood)(nil),  // 10: hannah.AgentSetResidentMood
	(*AgentSatelliteUpdate)(nil),  // 11: hannah.AgentSatelliteUpdate
	(*AgentSatelliteDeleted)(nil), // 12: hannah.AgentSatelliteDeleted
	(*AgentTextAnswer)(nil),       // 13: hannah.AgentTextAnswer
	(*AgentNotification)(nil),     // 14: hannah.AgentNotification
	(*AgentStateValue)(nil),       // 15: hannah.AgentStateValue
	(*AgentDevice)(nil),           // 16: hannah.AgentDevice
	(*AgentDeviceSnapshot)(nil),   // 17: hannah.AgentDeviceSnapshot
	(*AgentRoom)(nil),             // 18: hannah.AgentRoom
	(*AgentRoomSnapshot)(nil),     // 19: hannah.AgentRoomSnapshot
	(*AgentResident)(nil),         // 20: hannah.AgentResident
	(*AgentResidentSnapshot)(nil), // 21: hannah.AgentResidentSnapshot
	(*AgentAskResident)(nil),      // 22: hannah.AgentAskResident
	(*AgentResidentAnswered)(nil), // 23: hannah.AgentResidentAnswered
	(*AgentBleUpdate)(nil),        // 24: hannah.AgentBleUpdate
	(*AgentSensorUpdate)(nil),     // 25: hannah.AgentSensorUpdate
	nil,                           // 26: hannah.AgentDevice.RoomNamesEntry
	nil,                           // 27: hannah.AgentRoom.DisplayNamesEntry
}
var file_agent_proto_depIdxs = []int32{
	3,  // 0: hannah.AgentMessage.state_update:type_name -> hannah.AgentStateUpdate
	20, // 1: hannah.AgentMessage.resident_update:type_name -> hannah.AgentResident
	4,  // 2: hannah.AgentMessage.text_command:type_name -> hannah.AgentTextCommand
	2,  // 3: hannah.AgentMessage.satellite_control:type_name -> hannah.AgentSatelliteControl
	17, // 4: hannah.AgentMessage.send_snapshot:type_name -> hannah.AgentDeviceSnapshot
	21, // 5: hannah.AgentMessage.send_residents:type_name -> hannah.AgentResidentSnapshot
	22, // 6: hannah.AgentMessage.ask_resident:type_name -> hannah.AgentAskResident
	19, // 7: hannah.AgentMessage.send_rooms:type_name -> hannah.AgentRoomSnapshot
	7,  // 8: hannah.AgentCommand.set_state:type_name -> hannah.AgentSetState
	8,  // 9: hannah.AgentCommand.watch_more:type_name -> hannah.AgentWatchMore
	9,  // 10: hannah.AgentCommand.set_resident:type_name -> hannah.AgentSetResident
	11, // 11: hannah.AgentCommand.satellite_update:type_name -> hannah.AgentSatelliteUpdate
	13, // 12: hannah.AgentCommand.text_answer:type_name -> hannah.AgentTextAnswer
	6,  // 13: hannah.AgentCommand.firmware_event:type_name -> hannah.AgentFirmwareEvent
	24, // 14: hannah.AgentCommand.ble_update:type_name -> hannah.AgentBleUpdate
	25, // 15: hannah.AgentCommand.sensor_update:type_name -> hannah.AgentSensorUpdate
	23, // 16: hannah.AgentCommand.resident_answered:type_name -> hannah.AgentResidentAnswered
	12, // 17: hannah.AgentCommand.satellite_deleted:type_name -> hannah.AgentSatelliteDeleted
	10, // 18: hannah.AgentCommand.set_resident_mood:type_name -> hannah.AgentSetResidentMood
	0,  // 19: hannah.AgentSetResident.type:type_name -> hannah.ResidentType
	0,  // 20: hannah.AgentSetResidentMood.type:type_name -> hannah.ResidentType
	15, // 21: hannah.AgentDevice.value:type_name -> hannah.AgentStateValue
	26, // 22: hannah.AgentDevice.room_names:type_name -> hannah.AgentDevice.RoomNamesEntry
	16, // 23: hannah.AgentDeviceSnapshot.devices:type_name -> hannah.AgentDevice
	27, // 24: hannah.AgentRoom.display_names:type_name -> hannah.AgentRoom.DisplayNamesEntry
	18, // 25: hannah.AgentRoomSnapshot.rooms:type_name -> hannah.AgentRoom
	0,  // 26: hannah.AgentResident.type:type_name -> hannah.ResidentType
	20, // 27: hannah.AgentResidentSnapshot.residents:type_name -> hannah.AgentResident
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_StateUpdate)(nil),
		(*AgentMessage_ResidentUpdate)(nil),
		(*AgentMessage_TextCommand)(nil),
		(*AgentMessage_SatelliteControl)(nil),
		(*AgentMessage_SendSnapshot)(nil),
		(*AgentMessage_SendResidents)(nil),
		(*AgentMessage_AskResident)(nil),
		(*AgentMessage_SendRooms)(nil),
	}
	file_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*AgentSatelliteControl_Dnd)(nil),
		(*AgentSatelliteControl_Mute)(nil),
		(*AgentSatelliteControl_Volume)(nil),
		(*AgentSatelliteControl_Announcement)(nil),
		(*AgentSatelliteControl_AnnouncementSsml)(nil),
		(*AgentSatelliteControl_AnnouncementRephrase)(nil),
	}
	file_agent_proto_msgTypes[4].OneofWrappers = []any{
		(*AgentCommand_SetState)(nil),
		(*AgentCommand_WatchMore)(nil),
		(*AgentCommand_SetResident)(nil),
		(*AgentCommand_SatelliteUpdate)(nil),
		(*AgentCommand_TextAnswer)(nil),
		(*AgentCommand_FirmwareEvent)(nil),
		(*AgentCommand_BleUpdate)(nil),
		(*AgentCommand_SensorUpdate)(nil),
		(*AgentCommand_ResidentAnswered)(nil),
		(*AgentCommand_SatelliteDeleted)(nil),
		(*AgentCommand_SetResidentMood)(nil),
	}
	file_agent_proto_msgTypes[10].OneofWrappers = []any{}
	file_agent_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
