// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: car_state.proto

package hannah

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CarStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"` // false if no MQTT data received yet
	State         *CarStateProto         `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarStateResponse) Reset() {
	*x = CarStateResponse{}
	mi := &file_car_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarStateResponse) ProtoMessage() {}

func (x *CarStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_car_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarStateResponse.ProtoReflect.Descriptor instead.
func (*CarStateResponse) Descriptor() ([]byte, []int) {
	return file_car_state_proto_rawDescGZIP(), []int{0}
}

func (x *CarStateResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CarStateResponse) GetState() *CarStateProto {
	if x != nil {
		return x.State
	}
	return nil
}

type GetAllCarStatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	States        []*CarStateProto       `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllCarStatesResponse) Reset() {
	*x = GetAllCarStatesResponse{}
	mi := &file_car_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllCarStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllCarStatesResponse) ProtoMessage() {}

func (x *GetAllCarStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_car_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllCarStatesResponse.ProtoReflect.Descriptor instead.
func (*GetAllCarStatesResponse) Descriptor() ([]byte, []int) {
	return file_car_state_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllCarStatesResponse) GetStates() []*CarStateProto {
	if x != nil {
		return x.States
	}
	return nil
}

type CarStateProto struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// position
	Latitude     float32 `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude    float32 `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Address      string  `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	IsMoving     bool    `protobuf:"varint,4,opt,name=is_moving,json=isMoving,proto3" json:"is_moving,omitempty"`
	PositionDate int64   `protobuf:"varint,5,opt,name=position_date,json=positionDate,proto3" json:"position_date,omitempty"` // Unix timestamp (seconds)
	// status
	Odometer       int32  `protobuf:"varint,6,opt,name=odometer,proto3" json:"odometer,omitempty"`
	TotalRange     int32  `protobuf:"varint,7,opt,name=total_range,json=totalRange,proto3" json:"total_range,omitempty"`
	IsCarLocked    bool   `protobuf:"varint,8,opt,name=is_car_locked,json=isCarLocked,proto3" json:"is_car_locked,omitempty"`
	DoorLockStatus string `protobuf:"bytes,9,opt,name=door_lock_status,json=doorLockStatus,proto3" json:"door_lock_status,omitempty"`
	OverallStatus  string `protobuf:"bytes,10,opt,name=overall_status,json=overallStatus,proto3" json:"overall_status,omitempty"`
	// doors/windows: name → true (closed) / false (open)
	Doors   map[string]bool `protobuf:"bytes,11,rep,name=doors,proto3" json:"doors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Windows map[string]bool `protobuf:"bytes,12,rep,name=windows,proto3" json:"windows,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// Roomie-ID des Fahrzeughalters (leer = kein Owner-Filter)
	OwnerRoomie string `protobuf:"bytes,13,opt,name=owner_roomie,json=ownerRoomie,proto3" json:"owner_roomie,omitempty"`
	// Metadaten
	DisplayName   string `protobuf:"bytes,14,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // z.B. "Leonies Golf"
	Plate         string `protobuf:"bytes,15,opt,name=plate,proto3" json:"plate,omitempty"`                                // Nummernschild
	Vin           string `protobuf:"bytes,16,opt,name=vin,proto3" json:"vin,omitempty"`                                    // Fahrzeug-Identifikationsnummer
	HomeAddress   string `protobuf:"bytes,17,opt,name=home_address,json=homeAddress,proto3" json:"home_address,omitempty"` // Heimadresse für "steht zu Hause"-Erkennung
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarStateProto) Reset() {
	*x = CarStateProto{}
	mi := &file_car_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarStateProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarStateProto) ProtoMessage() {}

func (x *CarStateProto) ProtoReflect() protoreflect.Message {
	mi := &file_car_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarStateProto.ProtoReflect.Descriptor instead.
func (*CarStateProto) Descriptor() ([]byte, []int) {
	return file_car_state_proto_rawDescGZIP(), []int{2}
}

func (x *CarStateProto) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *CarStateProto) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *CarStateProto) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CarStateProto) GetIsMoving() bool {
	if x != nil {
		return x.IsMoving
	}
	return false
}

func (x *CarStateProto) GetPositionDate() int64 {
	if x != nil {
		return x.PositionDate
	}
	return 0
}

func (x *CarStateProto) GetOdometer() int32 {
	if x != nil {
		return x.Odometer
	}
	return 0
}

func (x *CarStateProto) GetTotalRange() int32 {
	if x != nil {
		return x.TotalRange
	}
	return 0
}

func (x *CarStateProto) GetIsCarLocked() bool {
	if x != nil {
		return x.IsCarLocked
	}
	return false
}

func (x *CarStateProto) GetDoorLockStatus() string {
	if x != nil {
		return x.DoorLockStatus
	}
	return ""
}

func (x *CarStateProto) GetOverallStatus() string {
	if x != nil {
		return x.OverallStatus
	}
	return ""
}

func (x *CarStateProto) GetDoors() map[string]bool {
	if x != nil {
		return x.Doors
	}
	return nil
}

func (x *CarStateProto) GetWindows() map[string]bool {
	if x != nil {
		return x.Windows
	}
	return nil
}

func (x *CarStateProto) GetOwnerRoomie() string {
	if x != nil {
		return x.OwnerRoomie
	}
	return ""
}

func (x *CarStateProto) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CarStateProto) GetPlate() string {
	if x != nil {
		return x.Plate
	}
	return ""
}

func (x *CarStateProto) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *CarStateProto) GetHomeAddress() string {
	if x != nil {
		return x.HomeAddress
	}
	return ""
}

var File_car_state_proto protoreflect.FileDescriptor

const file_car_state_proto_rawDesc = "" +
	"\n" +
	"\x0fcar_state.proto\x12\x06hannah\"]\n" +
	"\x10CarStateResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12+\n" +
	"\x05state\x18\x02 \x01(\v2\x15.hannah.CarStateProtoR\x05state\"H\n" +
	"\x17GetAllCarStatesResponse\x12-\n" +
	"\x06states\x18\x01 \x03(\v2\x15.hannah.CarStateProtoR\x06states\"\xd4\x05\n" +
	"\rCarStateProto\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x02R\tlongitude\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1b\n" +
	"\tis_moving\x18\x04 \x01(\bR\bisMoving\x12#\n" +
	"\rposition_date\x18\x05 \x01(\x03R\fpositionDate\x12\x1a\n" +
	"\bodometer\x18\x06 \x01(\x05R\bodometer\x12\x1f\n" +
	"\vtotal_range\x18\a \x01(\x05R\n" +
	"totalRange\x12\"\n" +
	"\ris_car_locked\x18\b \x01(\bR\visCarLocked\x12(\n" +
	"\x10door_lock_status\x18\t \x01(\tR\x0edoorLockStatus\x12%\n" +
	"\x0eoverall_status\x18\n" +
	" \x01(\tR\roverallStatus\x126\n" +
	"\x05doors\x18\v \x03(\v2 .hannah.CarStateProto.DoorsEntryR\x05doors\x12<\n" +
	"\awindows\x18\f \x03(\v2\".hannah.CarStateProto.WindowsEntryR\awindows\x12!\n" +
	"\fowner_roomie\x18\r \x01(\tR\vownerRoomie\x12!\n" +
	"\fdisplay_name\x18\x0e \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05plate\x18\x0f \x01(\tR\x05plate\x12\x10\n" +
	"\x03vin\x18\x10 \x01(\tR\x03vin\x12!\n" +
	"\fhome_address\x18\x11 \x01(\tR\vhomeAddress\x1a8\n" +
	"\n" +
	"DoorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a:\n" +
	"\fWindowsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01B=Z;dev.kernstock.net/gessinger/voice/hannah/proxy/proto/hannahb\x06proto3"

var (
	file_car_state_proto_rawDescOnce sync.Once
	file_car_state_proto_rawDescData []byte
)

func file_car_state_proto_rawDescGZIP() []byte {
	file_car_state_proto_rawDescOnce.Do(func() {
		file_car_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_car_state_proto_rawDesc), len(file_car_state_proto_rawDesc)))
	})
	return file_car_state_proto_rawDescData
}

var file_car_state_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_car_state_proto_goTypes = []any{
	(*CarStateResponse)(nil),        // 0: hannah.CarStateResponse
	(*GetAllCarStatesResponse)(nil), // 1: hannah.GetAllCarStatesResponse
	(*CarStateProto)(nil),           // 2: hannah.CarStateProto
	nil,                             // 3: hannah.CarStateProto.DoorsEntry
	nil,                             // 4: hannah.CarStateProto.WindowsEntry
}
var file_car_state_proto_depIdxs = []int32{
	2, // 0: hannah.CarStateResponse.state:type_name -> hannah.CarStateProto
	2, // 1: hannah.GetAllCarStatesResponse.states:type_name -> hannah.CarStateProto
	3, // 2: hannah.CarStateProto.doors:type_name -> hannah.CarStateProto.DoorsEntry
	4, // 3: hannah.CarStateProto.windows:type_name -> hannah.CarStateProto.WindowsEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_car_state_proto_init() }
func file_car_state_proto_init() {
	if File_car_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_car_state_proto_rawDesc), len(file_car_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_car_state_proto_goTypes,
		DependencyIndexes: file_car_state_proto_depIdxs,
		MessageInfos:      file_car_state_proto_msgTypes,
	}.Build()
	File_car_state_proto = out.File
	file_car_state_proto_goTypes = nil
	file_car_state_proto_depIdxs = nil
}
