// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: device_control_menu.proto

package hannah

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                     // full device prefix, e.g. "javascript.0.virtualDevice.Licht.EG.Wohnzimmer.DeckeSeite"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                                 // display name, e.g. "DeckeSeite"
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`                                                                         // e.g. "Licht", "Stecker", "Temperaturen"
	States        []string               `protobuf:"bytes,4,rep,name=states,proto3" json:"states,omitempty"`                                                                             // available state keys: "on", "level", "color", …
	Current       map[string]string      `protobuf:"bytes,5,rep,name=current,proto3" json:"current,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // current values as strings, e.g. {"on": "true", "level": "75"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_device_control_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_device_control_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_device_control_menu_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceInfo) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *DeviceInfo) GetStates() []string {
	if x != nil {
		return x.States
	}
	return nil
}

func (x *DeviceInfo) GetCurrent() map[string]string {
	if x != nil {
		return x.Current
	}
	return nil
}

type RoomInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`   // room_id (lowercase), e.g. "wohnzimmer"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // display name, e.g. "Wohnzimmer"
	Devices       []*DeviceInfo          `protobuf:"bytes,3,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_device_control_menu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_device_control_menu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_device_control_menu_proto_rawDescGZIP(), []int{1}
}

func (x *RoomInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *RoomInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomInfo) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type GetDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomInfo            `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDevicesResponse) Reset() {
	*x = GetDevicesResponse{}
	mi := &file_device_control_menu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDevicesResponse) ProtoMessage() {}

func (x *GetDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_device_control_menu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDevicesResponse.ProtoReflect.Descriptor instead.
func (*GetDevicesResponse) Descriptor() ([]byte, []int) {
	return file_device_control_menu_proto_rawDescGZIP(), []int{2}
}

func (x *GetDevicesResponse) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type ControlDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // DeviceInfo.id
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`                       // state key: "on", "level", "color"
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`                       // string-serialised value: "true", "false", "50", "#FF0000"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlDeviceRequest) Reset() {
	*x = ControlDeviceRequest{}
	mi := &file_device_control_menu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlDeviceRequest) ProtoMessage() {}

func (x *ControlDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_device_control_menu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlDeviceRequest.ProtoReflect.Descriptor instead.
func (*ControlDeviceRequest) Descriptor() ([]byte, []int) {
	return file_device_control_menu_proto_rawDescGZIP(), []int{3}
}

func (x *ControlDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ControlDeviceRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ControlDeviceRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_device_control_menu_proto protoreflect.FileDescriptor

const file_device_control_menu_proto_rawDesc = "" +
	"\n" +
	"\x19device_control_menu.proto\x12\x06hannah\"\xdb\x01\n" +
	"\n" +
	"DeviceInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x16\n" +
	"\x06states\x18\x04 \x03(\tR\x06states\x129\n" +
	"\acurrent\x18\x05 \x03(\v2\x1f.hannah.DeviceInfo.CurrentEntryR\acurrent\x1a:\n" +
	"\fCurrentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\bRoomInfo\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\adevices\x18\x03 \x03(\v2\x12.hannah.DeviceInfoR\adevices\"<\n" +
	"\x12GetDevicesResponse\x12&\n" +
	"\x05rooms\x18\x01 \x03(\v2\x10.hannah.RoomInfoR\x05rooms\"_\n" +
	"\x14ControlDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05valueB=Z;dev.kernstock.net/gessinger/voice/hannah/proxy/proto/hannahb\x06proto3"

var (
	file_device_control_menu_proto_rawDescOnce sync.Once
	file_device_control_menu_proto_rawDescData []byte
)

func file_device_control_menu_proto_rawDescGZIP() []byte {
	file_device_control_menu_proto_rawDescOnce.Do(func() {
		file_device_control_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_device_control_menu_proto_rawDesc), len(file_device_control_menu_proto_rawDesc)))
	})
	return file_device_control_menu_proto_rawDescData
}

var file_device_control_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_device_control_menu_proto_goTypes = []any{
	(*DeviceInfo)(nil),           // 0: hannah.DeviceInfo
	(*RoomInfo)(nil),             // 1: hannah.RoomInfo
	(*GetDevicesResponse)(nil),   // 2: hannah.GetDevicesResponse
	(*ControlDeviceRequest)(nil), // 3: hannah.ControlDeviceRequest
	nil,                          // 4: hannah.DeviceInfo.CurrentEntry
}
var file_device_control_menu_proto_depIdxs = []int32{
	4, // 0: hannah.DeviceInfo.current:type_name -> hannah.DeviceInfo.CurrentEntry
	0, // 1: hannah.RoomInfo.devices:type_name -> hannah.DeviceInfo
	1, // 2: hannah.GetDevicesResponse.rooms:type_name -> hannah.RoomInfo
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_device_control_menu_proto_init() }
func file_device_control_menu_proto_init() {
	if File_device_control_menu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_device_control_menu_proto_rawDesc), len(file_device_control_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_device_control_menu_proto_goTypes,
		DependencyIndexes: file_device_control_menu_proto_depIdxs,
		MessageInfos:      file_device_control_menu_proto_msgTypes,
	}.Build()
	File_device_control_menu_proto = out.File
	file_device_control_menu_proto_goTypes = nil
	file_device_control_menu_proto_depIdxs = nil
}
