// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: event_stream.proto

package hannah

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If empty, subscribe to all event types.
	EventTypes    []string `protobuf:"bytes,1,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFilter) Reset() {
	*x = EventFilter{}
	mi := &file_event_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFilter) ProtoMessage() {}

func (x *EventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_event_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFilter.ProtoReflect.Descriptor instead.
func (*EventFilter) Descriptor() ([]byte, []int) {
	return file_event_stream_proto_rawDescGZIP(), []int{0}
}

func (x *EventFilter) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type HannahEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	EventType string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "car.parked" | "resident.arrived" | "resident.departed" | "system.notification" | "satellite.firmware"
	Timestamp string                 `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // ISO 8601 UTC
	// Types that are valid to be assigned to Payload:
	//
	//	*HannahEvent_CarState
	//	*HannahEvent_ResidentEvent
	//	*HannahEvent_SystemNotification
	//	*HannahEvent_FirmwareEvent
	Payload       isHannahEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HannahEvent) Reset() {
	*x = HannahEvent{}
	mi := &file_event_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HannahEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HannahEvent) ProtoMessage() {}

func (x *HannahEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HannahEvent.ProtoReflect.Descriptor instead.
func (*HannahEvent) Descriptor() ([]byte, []int) {
	return file_event_stream_proto_rawDescGZIP(), []int{1}
}

func (x *HannahEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *HannahEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *HannahEvent) GetPayload() isHannahEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HannahEvent) GetCarState() *CarStateProto {
	if x != nil {
		if x, ok := x.Payload.(*HannahEvent_CarState); ok {
			return x.CarState
		}
	}
	return nil
}

func (x *HannahEvent) GetResidentEvent() *ResidentEventProto {
	if x != nil {
		if x, ok := x.Payload.(*HannahEvent_ResidentEvent); ok {
			return x.ResidentEvent
		}
	}
	return nil
}

func (x *HannahEvent) GetSystemNotification() *SystemNotificationEvent {
	if x != nil {
		if x, ok := x.Payload.(*HannahEvent_SystemNotification); ok {
			return x.SystemNotification
		}
	}
	return nil
}

func (x *HannahEvent) GetFirmwareEvent() *FirmwareEventProto {
	if x != nil {
		if x, ok := x.Payload.(*HannahEvent_FirmwareEvent); ok {
			return x.FirmwareEvent
		}
	}
	return nil
}

type isHannahEvent_Payload interface {
	isHannahEvent_Payload()
}

type HannahEvent_CarState struct {
	CarState *CarStateProto `protobuf:"bytes,10,opt,name=car_state,json=carState,proto3,oneof"`
}

type HannahEvent_ResidentEvent struct {
	ResidentEvent *ResidentEventProto `protobuf:"bytes,11,opt,name=resident_event,json=residentEvent,proto3,oneof"`
}

type HannahEvent_SystemNotification struct {
	SystemNotification *SystemNotificationEvent `protobuf:"bytes,12,opt,name=system_notification,json=systemNotification,proto3,oneof"`
}

type HannahEvent_FirmwareEvent struct {
	FirmwareEvent *FirmwareEventProto `protobuf:"bytes,13,opt,name=firmware_event,json=firmwareEvent,proto3,oneof"`
}

func (*HannahEvent_CarState) isHannahEvent_Payload() {}

func (*HannahEvent_ResidentEvent) isHannahEvent_Payload() {}

func (*HannahEvent_SystemNotification) isHannahEvent_Payload() {}

func (*HannahEvent_FirmwareEvent) isHannahEvent_Payload() {}

type SystemNotificationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"` // LLM-reformulierter Benachrichtigungstext
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemNotificationEvent) Reset() {
	*x = SystemNotificationEvent{}
	mi := &file_event_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemNotificationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemNotificationEvent) ProtoMessage() {}

func (x *SystemNotificationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemNotificationEvent.ProtoReflect.Descriptor instead.
func (*SystemNotificationEvent) Descriptor() ([]byte, []int) {
	return file_event_stream_proto_rawDescGZIP(), []int{2}
}

func (x *SystemNotificationEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type FirmwareEventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FirmwareEventProto) Reset() {
	*x = FirmwareEventProto{}
	mi := &file_event_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirmwareEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirmwareEventProto) ProtoMessage() {}

func (x *FirmwareEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_event_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirmwareEventProto.ProtoReflect.Descriptor instead.
func (*FirmwareEventProto) Descriptor() ([]byte, []int) {
	return file_event_stream_proto_rawDescGZIP(), []int{3}
}

func (x *FirmwareEventProto) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *FirmwareEventProto) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type TriggerFirmwareUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerFirmwareUpdateRequest) Reset() {
	*x = TriggerFirmwareUpdateRequest{}
	mi := &file_event_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerFirmwareUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerFirmwareUpdateRequest) ProtoMessage() {}

func (x *TriggerFirmwareUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerFirmwareUpdateRequest.ProtoReflect.Descriptor instead.
func (*TriggerFirmwareUpdateRequest) Descriptor() ([]byte, []int) {
	return file_event_stream_proto_rawDescGZIP(), []int{4}
}

func (x *TriggerFirmwareUpdateRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type ResidentEventProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomieId      string                 `protobuf:"bytes,1,opt,name=roomie_id,json=roomieId,proto3" json:"roomie_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Event         string                 `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"` // "arrived" | "departed"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResidentEventProto) Reset() {
	*x = ResidentEventProto{}
	mi := &file_event_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResidentEventProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResidentEventProto) ProtoMessage() {}

func (x *ResidentEventProto) ProtoReflect() protoreflect.Message {
	mi := &file_event_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResidentEventProto.ProtoReflect.Descriptor instead.
func (*ResidentEventProto) Descriptor() ([]byte, []int) {
	return file_event_stream_proto_rawDescGZIP(), []int{5}
}

func (x *ResidentEventProto) GetRoomieId() string {
	if x != nil {
		return x.RoomieId
	}
	return ""
}

func (x *ResidentEventProto) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ResidentEventProto) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

var File_event_stream_proto protoreflect.FileDescriptor

const file_event_stream_proto_rawDesc = "" +
	"\n" +
	"\x12event_stream.proto\x12\x06hannah\x1a\x0fcar_state.proto\".\n" +
	"\vEventFilter\x12\x1f\n" +
	"\vevent_types\x18\x01 \x03(\tR\n" +
	"eventTypes\"\xe9\x02\n" +
	"\vHannahEvent\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\tR\ttimestamp\x124\n" +
	"\tcar_state\x18\n" +
	" \x01(\v2\x15.hannah.CarStateProtoH\x00R\bcarState\x12C\n" +
	"\x0eresident_event\x18\v \x01(\v2\x1a.hannah.ResidentEventProtoH\x00R\rresidentEvent\x12R\n" +
	"\x13system_notification\x18\f \x01(\v2\x1f.hannah.SystemNotificationEventH\x00R\x12systemNotification\x12C\n" +
	"\x0efirmware_event\x18\r \x01(\v2\x1a.hannah.FirmwareEventProtoH\x00R\rfirmwareEventB\t\n" +
	"\apayload\"-\n" +
	"\x17SystemNotificationEvent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"F\n" +
	"\x12FirmwareEventProto\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"6\n" +
	"\x1cTriggerFirmwareUpdateRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\"j\n" +
	"\x12ResidentEventProto\x12\x1b\n" +
	"\troomie_id\x18\x01 \x01(\tR\broomieId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05event\x18\x03 \x01(\tR\x05eventB=Z;dev.kernstock.net/gessinger/voice/hannah/proxy/proto/hannahb\x06proto3"

var (
	file_event_stream_proto_rawDescOnce sync.Once
	file_event_stream_proto_rawDescData []byte
)

func file_event_stream_proto_rawDescGZIP() []byte {
	file_event_stream_proto_rawDescOnce.Do(func() {
		file_event_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_stream_proto_rawDesc), len(file_event_stream_proto_rawDesc)))
	})
	return file_event_stream_proto_rawDescData
}

var file_event_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_event_stream_proto_goTypes = []any{
	(*EventFilter)(nil),                  // 0: hannah.EventFilter
	(*HannahEvent)(nil),                  // 1: hannah.HannahEvent
	(*SystemNotificationEvent)(nil),      // 2: hannah.SystemNotificationEvent
	(*FirmwareEventProto)(nil),           // 3: hannah.FirmwareEventProto
	(*TriggerFirmwareUpdateRequest)(nil), // 4: hannah.TriggerFirmwareUpdateRequest
	(*ResidentEventProto)(nil),           // 5: hannah.ResidentEventProto
	(*CarStateProto)(nil),                // 6: hannah.CarStateProto
}
var file_event_stream_proto_depIdxs = []int32{
	6, // 0: hannah.HannahEvent.car_state:type_name -> hannah.CarStateProto
	5, // 1: hannah.HannahEvent.resident_event:type_name -> hannah.ResidentEventProto
	2, // 2: hannah.HannahEvent.system_notification:type_name -> hannah.SystemNotificationEvent
	3, // 3: hannah.HannahEvent.firmware_event:type_name -> hannah.FirmwareEventProto
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_event_stream_proto_init() }
func file_event_stream_proto_init() {
	if File_event_stream_proto != nil {
		return
	}
	file_car_state_proto_init()
	file_event_stream_proto_msgTypes[1].OneofWrappers = []any{
		(*HannahEvent_CarState)(nil),
		(*HannahEvent_ResidentEvent)(nil),
		(*HannahEvent_SystemNotification)(nil),
		(*HannahEvent_FirmwareEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_stream_proto_rawDesc), len(file_event_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_stream_proto_goTypes,
		DependencyIndexes: file_event_stream_proto_depIdxs,
		MessageInfos:      file_event_stream_proto_msgTypes,
	}.Build()
	File_event_stream_proto = out.File
	file_event_stream_proto_goTypes = nil
	file_event_stream_proto_depIdxs = nil
}
