// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: hannah.proto

package hannah

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_hannah_proto protoreflect.FileDescriptor

const file_hannah_proto_rawDesc = "" +
	"\n" +
	"\fhannah.proto\x12\x06hannah\x1a\fshared.proto\x1a\x13user_registry.proto\x1a\rcontrol.proto\x1a\x0fcar_state.proto\x1a\x12event_stream.proto\x1a\x15satellite_proxy.proto\x1a\x19device_control_menu.proto\x1a\x1csatellite_provisioning.proto\x1a\x18speaker_enrollment.proto\x1a\vagent.proto\x1a\x16wakeword_capture.proto\x1a\x13timer_service.proto2\xd7#\n" +
	"\rHannahService\x12=\n" +
	"\bGetUsers\x12\x17.hannah.GetUsersRequest\x1a\x18.hannah.GetUsersResponse\x127\n" +
	"\aGetUser\x12\x16.hannah.GetUserRequest\x1a\x14.hannah.UserResponse\x12A\n" +
	"\vLinkAccount\x12\x1a.hannah.LinkAccountRequest\x1a\x16.hannah.StatusResponse\x12E\n" +
	"\rUnlinkAccount\x12\x1c.hannah.UnlinkAccountRequest\x1a\x16.hannah.StatusResponse\x12E\n" +
	"\rSetTrustLevel\x12\x1c.hannah.SetTrustLevelRequest\x1a\x16.hannah.StatusResponse\x12M\n" +
	"\x11SetSystemMessages\x12 .hannah.SetSystemMessagesRequest\x1a\x16.hannah.StatusResponse\x123\n" +
	"\x05Login\x12\x14.hannah.LoginRequest\x1a\x14.hannah.UserResponse\x12C\n" +
	"\n" +
	"CreateUser\x12\x19.hannah.CreateUserRequest\x1a\x1a.hannah.CreateUserResponse\x12?\n" +
	"\n" +
	"UpdateUser\x12\x19.hannah.UpdateUserRequest\x1a\x16.hannah.StatusResponse\x12?\n" +
	"\n" +
	"DeleteUser\x12\x19.hannah.DeleteUserRequest\x1a\x16.hannah.StatusResponse\x12;\n" +
	"\fGetResidents\x12\r.hannah.Empty\x1a\x1c.hannah.GetResidentsResponse\x127\n" +
	"\n" +
	"GetDevices\x12\r.hannah.Empty\x1a\x1a.hannah.GetDevicesResponse\x12E\n" +
	"\rControlDevice\x12\x1c.hannah.ControlDeviceRequest\x1a\x16.hannah.StatusResponse\x12C\n" +
	"\n" +
	"SubmitText\x12\x19.hannah.SubmitTextRequest\x1a\x1a.hannah.SubmitTextResponse\x12F\n" +
	"\vSubmitVoice\x12\x1a.hannah.SubmitVoiceRequest\x1a\x1b.hannah.SubmitVoiceResponse\x12;\n" +
	"\bAnnounce\x12\x17.hannah.AnnounceRequest\x1a\x16.hannah.StatusResponse\x12;\n" +
	"\x06Notify\x12\x19.hannah.AgentNotification\x1a\x16.hannah.StatusResponse\x12=\n" +
	"\rGetSatellites\x12\r.hannah.Empty\x1a\x1d.hannah.GetSatellitesResponse\x12K\n" +
	"\x10SetSatelliteRoom\x12\x1f.hannah.SetSatelliteRoomRequest\x1a\x16.hannah.StatusResponse\x12Y\n" +
	"\x17SetSatelliteDisplayName\x12&.hannah.SetSatelliteDisplayNameRequest\x1a\x16.hannah.StatusResponse\x12M\n" +
	"\x11SetSatelliteOwner\x12 .hannah.SetSatelliteOwnerRequest\x1a\x16.hannah.StatusResponse\x12I\n" +
	"\x0fDeleteSatellite\x12\x1e.hannah.DeleteSatelliteRequest\x1a\x16.hannah.StatusResponse\x123\n" +
	"\bGetRooms\x12\r.hannah.Empty\x1a\x18.hannah.GetRoomsResponse\x125\n" +
	"\tGetGroups\x12\r.hannah.Empty\x1a\x19.hannah.GetGroupsResponse\x12A\n" +
	"\vCreateGroup\x12\x1a.hannah.CreateGroupRequest\x1a\x16.hannah.StatusResponse\x12A\n" +
	"\vUpdateGroup\x12\x1a.hannah.UpdateGroupRequest\x1a\x16.hannah.StatusResponse\x12A\n" +
	"\vDeleteGroup\x12\x1a.hannah.DeleteGroupRequest\x1a\x16.hannah.StatusResponse\x12E\n" +
	"\rSetGroupRooms\x12\x1c.hannah.SetGroupRoomsRequest\x1a\x16.hannah.StatusResponse\x129\n" +
	"\vGetRoutines\x12\r.hannah.Empty\x1a\x1b.hannah.GetRoutinesResponse\x12L\n" +
	"\rCreateRoutine\x12\x1c.hannah.CreateRoutineRequest\x1a\x1d.hannah.CreateRoutineResponse\x12E\n" +
	"\rUpdateRoutine\x12\x1c.hannah.UpdateRoutineRequest\x1a\x16.hannah.StatusResponse\x12E\n" +
	"\rDeleteRoutine\x12\x1c.hannah.DeleteRoutineRequest\x1a\x16.hannah.StatusResponse\x129\n" +
	"\vGetTriggers\x12\r.hannah.Empty\x1a\x1b.hannah.GetTriggersResponse\x12E\n" +
	"\rCreateTrigger\x12\x1c.hannah.CreateTriggerRequest\x1a\x16.hannah.StatusResponse\x12E\n" +
	"\rUpdateTrigger\x12\x1c.hannah.UpdateTriggerRequest\x1a\x16.hannah.StatusResponse\x12E\n" +
	"\rDeleteTrigger\x12\x1c.hannah.DeleteTriggerRequest\x1a\x16.hannah.StatusResponse\x125\n" +
	"\tGetAlarms\x12\r.hannah.Empty\x1a\x19.hannah.GetAlarmsResponse\x12F\n" +
	"\vCreateAlarm\x12\x1a.hannah.CreateAlarmRequest\x1a\x1b.hannah.CreateAlarmResponse\x12A\n" +
	"\vUpdateAlarm\x12\x1a.hannah.UpdateAlarmRequest\x1a\x16.hannah.StatusResponse\x12A\n" +
	"\vDeleteAlarm\x12\x1a.hannah.DeleteAlarmRequest\x1a\x16.hannah.StatusResponse\x129\n" +
	"\vGetSettings\x12\r.hannah.Empty\x1a\x1b.hannah.GetSettingsResponse\x12C\n" +
	"\fUpdateConfig\x12\x1b.hannah.UpdateConfigRequest\x1a\x16.hannah.StatusResponse\x127\n" +
	"\n" +
	"GetBleTags\x12\r.hannah.Empty\x1a\x1a.hannah.GetBleTagsResponse\x12I\n" +
	"\fCreateBleTag\x12\x1b.hannah.CreateBleTagRequest\x1a\x1c.hannah.CreateBleTagResponse\x12C\n" +
	"\fUpdateBleTag\x12\x1b.hannah.UpdateBleTagRequest\x1a\x16.hannah.StatusResponse\x12C\n" +
	"\fDeleteBleTag\x12\x1b.hannah.DeleteBleTagRequest\x1a\x16.hannah.StatusResponse\x121\n" +
	"\aGetCars\x12\r.hannah.Empty\x1a\x17.hannah.GetCarsResponse\x12@\n" +
	"\tCreateCar\x12\x18.hannah.CreateCarRequest\x1a\x19.hannah.CreateCarResponse\x12=\n" +
	"\tUpdateCar\x12\x18.hannah.UpdateCarRequest\x1a\x16.hannah.StatusResponse\x12=\n" +
	"\tDeleteCar\x12\x18.hannah.DeleteCarRequest\x1a\x16.hannah.StatusResponse\x126\n" +
	"\vGetCarState\x12\r.hannah.Empty\x1a\x18.hannah.CarStateResponse\x12A\n" +
	"\x0fGetAllCarStates\x12\r.hannah.Empty\x1a\x1f.hannah.GetAllCarStatesResponse\x12=\n" +
	"\x0fSubscribeEvents\x12\x13.hannah.EventFilter\x1a\x13.hannah.HannahEvent0\x01\x12U\n" +
	"\x15TriggerFirmwareUpdate\x12$.hannah.TriggerFirmwareUpdateRequest\x1a\x16.hannah.StatusResponse\x12\\\n" +
	"\x17RequestSatelliteCapture\x12\x1f.hannah.SatelliteCaptureRequest\x1a .hannah.SatelliteCaptureResponse\x12R\n" +
	"\x17ReleaseSatelliteCapture\x12\x1f.hannah.SatelliteCaptureRequest\x1a\x16.hannah.StatusResponse\x12V\n" +
	"\x14StreamSatelliteAudio\x12\x1f.hannah.SatelliteCaptureRequest\x1a\x1b.hannah.SatelliteAudioChunk0\x01\x12C\n" +
	"\fTriggerPlink\x12\x1b.hannah.TriggerPlinkRequest\x1a\x16.hannah.StatusResponse\x12A\n" +
	"\rRegisterProxy\x12\x16.hannah.ProxyHeartbeat\x1a\x14.hannah.ProxyCommand(\x010\x01\x12a\n" +
	"\x14SubmitSatelliteAudio\x12#.hannah.SubmitSatelliteAudioRequest\x1a$.hannah.SubmitSatelliteAudioResponse\x12R\n" +
	"\x19NotifySatelliteRegistered\x12\x1d.hannah.SatelliteRegistration\x1a\x16.hannah.StatusResponse\x12L\n" +
	"\x13NotifySatelliteGone\x12\x1d.hannah.SatelliteRegistration\x1a\x16.hannah.StatusResponse\x12O\n" +
	"\x12ProvisionSatellite\x12!.hannah.ProvisionSatelliteRequest\x1a\x16.hannah.StatusResponse\x12K\n" +
	"\x10EnrollVoiceprint\x12\x1f.hannah.EnrollVoiceprintRequest\x1a\x16.hannah.StatusResponse\x12>\n" +
	"\fTimerConnect\x12\x14.hannah.TimerMessage\x1a\x14.hannah.TimerCommand(\x010\x01\x12>\n" +
	"\fAgentConnect\x12\x14.hannah.AgentMessage\x1a\x14.hannah.AgentCommand(\x010\x01BU\n" +
	"\tio.hannahB\vHannahProtoZ;dev.kernstock.net/gessinger/voice/hannah/proxy/proto/hannahb\x06proto3"

var file_hannah_proto_goTypes = []any{
	(*GetUsersRequest)(nil),                // 0: hannah.GetUsersRequest
	(*GetUserRequest)(nil),                 // 1: hannah.GetUserRequest
	(*LinkAccountRequest)(nil),             // 2: hannah.LinkAccountRequest
	(*UnlinkAccountRequest)(nil),           // 3: hannah.UnlinkAccountRequest
	(*SetTrustLevelRequest)(nil),           // 4: hannah.SetTrustLevelRequest
	(*SetSystemMessagesRequest)(nil),       // 5: hannah.SetSystemMessagesRequest
	(*LoginRequest)(nil),                   // 6: hannah.LoginRequest
	(*CreateUserRequest)(nil),              // 7: hannah.CreateUserRequest
	(*UpdateUserRequest)(nil),              // 8: hannah.UpdateUserRequest
	(*DeleteUserRequest)(nil),              // 9: hannah.DeleteUserRequest
	(*Empty)(nil),                          // 10: hannah.Empty
	(*ControlDeviceRequest)(nil),           // 11: hannah.ControlDeviceRequest
	(*SubmitTextRequest)(nil),              // 12: hannah.SubmitTextRequest
	(*SubmitVoiceRequest)(nil),             // 13: hannah.SubmitVoiceRequest
	(*AnnounceRequest)(nil),                // 14: hannah.AnnounceRequest
	(*AgentNotification)(nil),              // 15: hannah.AgentNotification
	(*SetSatelliteRoomRequest)(nil),        // 16: hannah.SetSatelliteRoomRequest
	(*SetSatelliteDisplayNameRequest)(nil), // 17: hannah.SetSatelliteDisplayNameRequest
	(*SetSatelliteOwnerRequest)(nil),       // 18: hannah.SetSatelliteOwnerRequest
	(*DeleteSatelliteRequest)(nil),         // 19: hannah.DeleteSatelliteRequest
	(*CreateGroupRequest)(nil),             // 20: hannah.CreateGroupRequest
	(*UpdateGroupRequest)(nil),             // 21: hannah.UpdateGroupRequest
	(*DeleteGroupRequest)(nil),             // 22: hannah.DeleteGroupRequest
	(*SetGroupRoomsRequest)(nil),           // 23: hannah.SetGroupRoomsRequest
	(*CreateRoutineRequest)(nil),           // 24: hannah.CreateRoutineRequest
	(*UpdateRoutineRequest)(nil),           // 25: hannah.UpdateRoutineRequest
	(*DeleteRoutineRequest)(nil),           // 26: hannah.DeleteRoutineRequest
	(*CreateTriggerRequest)(nil),           // 27: hannah.CreateTriggerRequest
	(*UpdateTriggerRequest)(nil),           // 28: hannah.UpdateTriggerRequest
	(*DeleteTriggerRequest)(nil),           // 29: hannah.DeleteTriggerRequest
	(*CreateAlarmRequest)(nil),             // 30: hannah.CreateAlarmRequest
	(*UpdateAlarmRequest)(nil),             // 31: hannah.UpdateAlarmRequest
	(*DeleteAlarmRequest)(nil),             // 32: hannah.DeleteAlarmRequest
	(*UpdateConfigRequest)(nil),            // 33: hannah.UpdateConfigRequest
	(*CreateBleTagRequest)(nil),            // 34: hannah.CreateBleTagRequest
	(*UpdateBleTagRequest)(nil),            // 35: hannah.UpdateBleTagRequest
	(*DeleteBleTagRequest)(nil),            // 36: hannah.DeleteBleTagRequest
	(*CreateCarRequest)(nil),               // 37: hannah.CreateCarRequest
	(*UpdateCarRequest)(nil),               // 38: hannah.UpdateCarRequest
	(*DeleteCarRequest)(nil),               // 39: hannah.DeleteCarRequest
	(*EventFilter)(nil),                    // 40: hannah.EventFilter
	(*TriggerFirmwareUpdateRequest)(nil),   // 41: hannah.TriggerFirmwareUpdateRequest
	(*SatelliteCaptureRequest)(nil),        // 42: hannah.SatelliteCaptureRequest
	(*TriggerPlinkRequest)(nil),            // 43: hannah.TriggerPlinkRequest
	(*ProxyHeartbeat)(nil),                 // 44: hannah.ProxyHeartbeat
	(*SubmitSatelliteAudioRequest)(nil),    // 45: hannah.SubmitSatelliteAudioRequest
	(*SatelliteRegistration)(nil),          // 46: hannah.SatelliteRegistration
	(*ProvisionSatelliteRequest)(nil),      // 47: hannah.ProvisionSatelliteRequest
	(*EnrollVoiceprintRequest)(nil),        // 48: hannah.EnrollVoiceprintRequest
	(*TimerMessage)(nil),                   // 49: hannah.TimerMessage
	(*AgentMessage)(nil),                   // 50: hannah.AgentMessage
	(*GetUsersResponse)(nil),               // 51: hannah.GetUsersResponse
	(*UserResponse)(nil),                   // 52: hannah.UserResponse
	(*StatusResponse)(nil),                 // 53: hannah.StatusResponse
	(*CreateUserResponse)(nil),             // 54: hannah.CreateUserResponse
	(*GetResidentsResponse)(nil),           // 55: hannah.GetResidentsResponse
	(*GetDevicesResponse)(nil),             // 56: hannah.GetDevicesResponse
	(*SubmitTextResponse)(nil),             // 57: hannah.SubmitTextResponse
	(*SubmitVoiceResponse)(nil),            // 58: hannah.SubmitVoiceResponse
	(*GetSatellitesResponse)(nil),          // 59: hannah.GetSatellitesResponse
	(*GetRoomsResponse)(nil),               // 60: hannah.GetRoomsResponse
	(*GetGroupsResponse)(nil),              // 61: hannah.GetGroupsResponse
	(*GetRoutinesResponse)(nil),            // 62: hannah.GetRoutinesResponse
	(*CreateRoutineResponse)(nil),          // 63: hannah.CreateRoutineResponse
	(*GetTriggersResponse)(nil),            // 64: hannah.GetTriggersResponse
	(*GetAlarmsResponse)(nil),              // 65: hannah.GetAlarmsResponse
	(*CreateAlarmResponse)(nil),            // 66: hannah.CreateAlarmResponse
	(*GetSettingsResponse)(nil),            // 67: hannah.GetSettingsResponse
	(*GetBleTagsResponse)(nil),             // 68: hannah.GetBleTagsResponse
	(*CreateBleTagResponse)(nil),           // 69: hannah.CreateBleTagResponse
	(*GetCarsResponse)(nil),                // 70: hannah.GetCarsResponse
	(*CreateCarResponse)(nil),              // 71: hannah.CreateCarResponse
	(*CarStateResponse)(nil),               // 72: hannah.CarStateResponse
	(*GetAllCarStatesResponse)(nil),        // 73: hannah.GetAllCarStatesResponse
	(*HannahEvent)(nil),                    // 74: hannah.HannahEvent
	(*SatelliteCaptureResponse)(nil),       // 75: hannah.SatelliteCaptureResponse
	(*SatelliteAudioChunk)(nil),            // 76: hannah.SatelliteAudioChunk
	(*ProxyCommand)(nil),                   // 77: hannah.ProxyCommand
	(*SubmitSatelliteAudioResponse)(nil),   // 78: hannah.SubmitSatelliteAudioResponse
	(*TimerCommand)(nil),                   // 79: hannah.TimerCommand
	(*AgentCommand)(nil),                   // 80: hannah.AgentCommand
}
var file_hannah_proto_depIdxs = []int32{
	0,  // 0: hannah.HannahService.GetUsers:input_type -> hannah.GetUsersRequest
	1,  // 1: hannah.HannahService.GetUser:input_type -> hannah.GetUserRequest
	2,  // 2: hannah.HannahService.LinkAccount:input_type -> hannah.LinkAccountRequest
	3,  // 3: hannah.HannahService.UnlinkAccount:input_type -> hannah.UnlinkAccountRequest
	4,  // 4: hannah.HannahService.SetTrustLevel:input_type -> hannah.SetTrustLevelRequest
	5,  // 5: hannah.HannahService.SetSystemMessages:input_type -> hannah.SetSystemMessagesRequest
	6,  // 6: hannah.HannahService.Login:input_type -> hannah.LoginRequest
	7,  // 7: hannah.HannahService.CreateUser:input_type -> hannah.CreateUserRequest
	8,  // 8: hannah.HannahService.UpdateUser:input_type -> hannah.UpdateUserRequest
	9,  // 9: hannah.HannahService.DeleteUser:input_type -> hannah.DeleteUserRequest
	10, // 10: hannah.HannahService.GetResidents:input_type -> hannah.Empty
	10, // 11: hannah.HannahService.GetDevices:input_type -> hannah.Empty
	11, // 12: hannah.HannahService.ControlDevice:input_type -> hannah.ControlDeviceRequest
	12, // 13: hannah.HannahService.SubmitText:input_type -> hannah.SubmitTextRequest
	13, // 14: hannah.HannahService.SubmitVoice:input_type -> hannah.SubmitVoiceRequest
	14, // 15: hannah.HannahService.Announce:input_type -> hannah.AnnounceRequest
	15, // 16: hannah.HannahService.Notify:input_type -> hannah.AgentNotification
	10, // 17: hannah.HannahService.GetSatellites:input_type -> hannah.Empty
	16, // 18: hannah.HannahService.SetSatelliteRoom:input_type -> hannah.SetSatelliteRoomRequest
	17, // 19: hannah.HannahService.SetSatelliteDisplayName:input_type -> hannah.SetSatelliteDisplayNameRequest
	18, // 20: hannah.HannahService.SetSatelliteOwner:input_type -> hannah.SetSatelliteOwnerRequest
	19, // 21: hannah.HannahService.DeleteSatellite:input_type -> hannah.DeleteSatelliteRequest
	10, // 22: hannah.HannahService.GetRooms:input_type -> hannah.Empty
	10, // 23: hannah.HannahService.GetGroups:input_type -> hannah.Empty
	20, // 24: hannah.HannahService.CreateGroup:input_type -> hannah.CreateGroupRequest
	21, // 25: hannah.HannahService.UpdateGroup:input_type -> hannah.UpdateGroupRequest
	22, // 26: hannah.HannahService.DeleteGroup:input_type -> hannah.DeleteGroupRequest
	23, // 27: hannah.HannahService.SetGroupRooms:input_type -> hannah.SetGroupRoomsRequest
	10, // 28: hannah.HannahService.GetRoutines:input_type -> hannah.Empty
	24, // 29: hannah.HannahService.CreateRoutine:input_type -> hannah.CreateRoutineRequest
	25, // 30: hannah.HannahService.UpdateRoutine:input_type -> hannah.UpdateRoutineRequest
	26, // 31: hannah.HannahService.DeleteRoutine:input_type -> hannah.DeleteRoutineRequest
	10, // 32: hannah.HannahService.GetTriggers:input_type -> hannah.Empty
	27, // 33: hannah.HannahService.CreateTrigger:input_type -> hannah.CreateTriggerRequest
	28, // 34: hannah.HannahService.UpdateTrigger:input_type -> hannah.UpdateTriggerRequest
	29, // 35: hannah.HannahService.DeleteTrigger:input_type -> hannah.DeleteTriggerRequest
	10, // 36: hannah.HannahService.GetAlarms:input_type -> hannah.Empty
	30, // 37: hannah.HannahService.CreateAlarm:input_type -> hannah.CreateAlarmRequest
	31, // 38: hannah.HannahService.UpdateAlarm:input_type -> hannah.UpdateAlarmRequest
	32, // 39: hannah.HannahService.DeleteAlarm:input_type -> hannah.DeleteAlarmRequest
	10, // 40: hannah.HannahService.GetSettings:input_type -> hannah.Empty
	33, // 41: hannah.HannahService.UpdateConfig:input_type -> hannah.UpdateConfigRequest
	10, // 42: hannah.HannahService.GetBleTags:input_type -> hannah.Empty
	34, // 43: hannah.HannahService.CreateBleTag:input_type -> hannah.CreateBleTagRequest
	35, // 44: hannah.HannahService.UpdateBleTag:input_type -> hannah.UpdateBleTagRequest
	36, // 45: hannah.HannahService.DeleteBleTag:input_type -> hannah.DeleteBleTagRequest
	10, // 46: hannah.HannahService.GetCars:input_type -> hannah.Empty
	37, // 47: hannah.HannahService.CreateCar:input_type -> hannah.CreateCarRequest
	38, // 48: hannah.HannahService.UpdateCar:input_type -> hannah.UpdateCarRequest
	39, // 49: hannah.HannahService.DeleteCar:input_type -> hannah.DeleteCarRequest
	10, // 50: hannah.HannahService.GetCarState:input_type -> hannah.Empty
	10, // 51: hannah.HannahService.GetAllCarStates:input_type -> hannah.Empty
	40, // 52: hannah.HannahService.SubscribeEvents:input_type -> hannah.EventFilter
	41, // 53: hannah.HannahService.TriggerFirmwareUpdate:input_type -> hannah.TriggerFirmwareUpdateRequest
	42, // 54: hannah.HannahService.RequestSatelliteCapture:input_type -> hannah.SatelliteCaptureRequest
	42, // 55: hannah.HannahService.ReleaseSatelliteCapture:input_type -> hannah.SatelliteCaptureRequest
	42, // 56: hannah.HannahService.StreamSatelliteAudio:input_type -> hannah.SatelliteCaptureRequest
	43, // 57: hannah.HannahService.TriggerPlink:input_type -> hannah.TriggerPlinkRequest
	44, // 58: hannah.HannahService.RegisterProxy:input_type -> hannah.ProxyHeartbeat
	45, // 59: hannah.HannahService.SubmitSatelliteAudio:input_type -> hannah.SubmitSatelliteAudioRequest
	46, // 60: hannah.HannahService.NotifySatelliteRegistered:input_type -> hannah.SatelliteRegistration
	46, // 61: hannah.HannahService.NotifySatelliteGone:input_type -> hannah.SatelliteRegistration
	47, // 62: hannah.HannahService.ProvisionSatellite:input_type -> hannah.ProvisionSatelliteRequest
	48, // 63: hannah.HannahService.EnrollVoiceprint:input_type -> hannah.EnrollVoiceprintRequest
	49, // 64: hannah.HannahService.TimerConnect:input_type -> hannah.TimerMessage
	50, // 65: hannah.HannahService.AgentConnect:input_type -> hannah.AgentMessage
	51, // 66: hannah.HannahService.GetUsers:output_type -> hannah.GetUsersResponse
	52, // 67: hannah.HannahService.GetUser:output_type -> hannah.UserResponse
	53, // 68: hannah.HannahService.LinkAccount:output_type -> hannah.StatusResponse
	53, // 69: hannah.HannahService.UnlinkAccount:output_type -> hannah.StatusResponse
	53, // 70: hannah.HannahService.SetTrustLevel:output_type -> hannah.StatusResponse
	53, // 71: hannah.HannahService.SetSystemMessages:output_type -> hannah.StatusResponse
	52, // 72: hannah.HannahService.Login:output_type -> hannah.UserResponse
	54, // 73: hannah.HannahService.CreateUser:output_type -> hannah.CreateUserResponse
	53, // 74: hannah.HannahService.UpdateUser:output_type -> hannah.StatusResponse
	53, // 75: hannah.HannahService.DeleteUser:output_type -> hannah.StatusResponse
	55, // 76: hannah.HannahService.GetResidents:output_type -> hannah.GetResidentsResponse
	56, // 77: hannah.HannahService.GetDevices:output_type -> hannah.GetDevicesResponse
	53, // 78: hannah.HannahService.ControlDevice:output_type -> hannah.StatusResponse
	57, // 79: hannah.HannahService.SubmitText:output_type -> hannah.SubmitTextResponse
	58, // 80: hannah.HannahService.SubmitVoice:output_type -> hannah.SubmitVoiceResponse
	53, // 81: hannah.HannahService.Announce:output_type -> hannah.StatusResponse
	53, // 82: hannah.HannahService.Notify:output_type -> hannah.StatusResponse
	59, // 83: hannah.HannahService.GetSatellites:output_type -> hannah.GetSatellitesResponse
	53, // 84: hannah.HannahService.SetSatelliteRoom:output_type -> hannah.StatusResponse
	53, // 85: hannah.HannahService.SetSatelliteDisplayName:output_type -> hannah.StatusResponse
	53, // 86: hannah.HannahService.SetSatelliteOwner:output_type -> hannah.StatusResponse
	53, // 87: hannah.HannahService.DeleteSatellite:output_type -> hannah.StatusResponse
	60, // 88: hannah.HannahService.GetRooms:output_type -> hannah.GetRoomsResponse
	61, // 89: hannah.HannahService.GetGroups:output_type -> hannah.GetGroupsResponse
	53, // 90: hannah.HannahService.CreateGroup:output_type -> hannah.StatusResponse
	53, // 91: hannah.HannahService.UpdateGroup:output_type -> hannah.StatusResponse
	53, // 92: hannah.HannahService.DeleteGroup:output_type -> hannah.StatusResponse
	53, // 93: hannah.HannahService.SetGroupRooms:output_type -> hannah.StatusResponse
	62, // 94: hannah.HannahService.GetRoutines:output_type -> hannah.GetRoutinesResponse
	63, // 95: hannah.HannahService.CreateRoutine:output_type -> hannah.CreateRoutineResponse
	53, // 96: hannah.HannahService.UpdateRoutine:output_type -> hannah.StatusResponse
	53, // 97: hannah.HannahService.DeleteRoutine:output_type -> hannah.StatusResponse
	64, // 98: hannah.HannahService.GetTriggers:output_type -> hannah.GetTriggersResponse
	53, // 99: hannah.HannahService.CreateTrigger:output_type -> hannah.StatusResponse
	53, // 100: hannah.HannahService.UpdateTrigger:output_type -> hannah.StatusResponse
	53, // 101: hannah.HannahService.DeleteTrigger:output_type -> hannah.StatusResponse
	65, // 102: hannah.HannahService.GetAlarms:output_type -> hannah.GetAlarmsResponse
	66, // 103: hannah.HannahService.CreateAlarm:output_type -> hannah.CreateAlarmResponse
	53, // 104: hannah.HannahService.UpdateAlarm:output_type -> hannah.StatusResponse
	53, // 105: hannah.HannahService.DeleteAlarm:output_type -> hannah.StatusResponse
	67, // 106: hannah.HannahService.GetSettings:output_type -> hannah.GetSettingsResponse
	53, // 107: hannah.HannahService.UpdateConfig:output_type -> hannah.StatusResponse
	68, // 108: hannah.HannahService.GetBleTags:output_type -> hannah.GetBleTagsResponse
	69, // 109: hannah.HannahService.CreateBleTag:output_type -> hannah.CreateBleTagResponse
	53, // 110: hannah.HannahService.UpdateBleTag:output_type -> hannah.StatusResponse
	53, // 111: hannah.HannahService.DeleteBleTag:output_type -> hannah.StatusResponse
	70, // 112: hannah.HannahService.GetCars:output_type -> hannah.GetCarsResponse
	71, // 113: hannah.HannahService.CreateCar:output_type -> hannah.CreateCarResponse
	53, // 114: hannah.HannahService.UpdateCar:output_type -> hannah.StatusResponse
	53, // 115: hannah.HannahService.DeleteCar:output_type -> hannah.StatusResponse
	72, // 116: hannah.HannahService.GetCarState:output_type -> hannah.CarStateResponse
	73, // 117: hannah.HannahService.GetAllCarStates:output_type -> hannah.GetAllCarStatesResponse
	74, // 118: hannah.HannahService.SubscribeEvents:output_type -> hannah.HannahEvent
	53, // 119: hannah.HannahService.TriggerFirmwareUpdate:output_type -> hannah.StatusResponse
	75, // 120: hannah.HannahService.RequestSatelliteCapture:output_type -> hannah.SatelliteCaptureResponse
	53, // 121: hannah.HannahService.ReleaseSatelliteCapture:output_type -> hannah.StatusResponse
	76, // 122: hannah.HannahService.StreamSatelliteAudio:output_type -> hannah.SatelliteAudioChunk
	53, // 123: hannah.HannahService.TriggerPlink:output_type -> hannah.StatusResponse
	77, // 124: hannah.HannahService.RegisterProxy:output_type -> hannah.ProxyCommand
	78, // 125: hannah.HannahService.SubmitSatelliteAudio:output_type -> hannah.SubmitSatelliteAudioResponse
	53, // 126: hannah.HannahService.NotifySatelliteRegistered:output_type -> hannah.StatusResponse
	53, // 127: hannah.HannahService.NotifySatelliteGone:output_type -> hannah.StatusResponse
	53, // 128: hannah.HannahService.ProvisionSatellite:output_type -> hannah.StatusResponse
	53, // 129: hannah.HannahService.EnrollVoiceprint:output_type -> hannah.StatusResponse
	79, // 130: hannah.HannahService.TimerConnect:output_type -> hannah.TimerCommand
	80, // 131: hannah.HannahService.AgentConnect:output_type -> hannah.AgentCommand
	66, // [66:132] is the sub-list for method output_type
	0,  // [0:66] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_hannah_proto_init() }
func file_hannah_proto_init() {
	if File_hannah_proto != nil {
		return
	}
	file_shared_proto_init()
	file_user_registry_proto_init()
	file_control_proto_init()
	file_car_state_proto_init()
	file_event_stream_proto_init()
	file_satellite_proxy_proto_init()
	file_device_control_menu_proto_init()
	file_satellite_provisioning_proto_init()
	file_speaker_enrollment_proto_init()
	file_agent_proto_init()
	file_wakeword_capture_proto_init()
	file_timer_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hannah_proto_rawDesc), len(file_hannah_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hannah_proto_goTypes,
		DependencyIndexes: file_hannah_proto_depIdxs,
	}.Build()
	File_hannah_proto = out.File
	file_hannah_proto_goTypes = nil
	file_hannah_proto_depIdxs = nil
}
