// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: satellite_provisioning.proto

package hannah

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sent by the ioBroker adapter (WebFlasher) before flashing a satellite.
// Hannah stores the seed + pre-config; when the satellite first connects with
// this seed, Hannah links the hardware serial to the pre-config and clears the seed.
type ProvisionSatelliteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          string                 `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`                                  // random UUID, also written to NVS during flash
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"` // pre-configured display name
	RoomId        string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`                // optional: pre-configured room (room_id from ioBroker)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProvisionSatelliteRequest) Reset() {
	*x = ProvisionSatelliteRequest{}
	mi := &file_satellite_provisioning_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProvisionSatelliteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionSatelliteRequest) ProtoMessage() {}

func (x *ProvisionSatelliteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_provisioning_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionSatelliteRequest.ProtoReflect.Descriptor instead.
func (*ProvisionSatelliteRequest) Descriptor() ([]byte, []int) {
	return file_satellite_provisioning_proto_rawDescGZIP(), []int{0}
}

func (x *ProvisionSatelliteRequest) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *ProvisionSatelliteRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ProvisionSatelliteRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

var File_satellite_provisioning_proto protoreflect.FileDescriptor

const file_satellite_provisioning_proto_rawDesc = "" +
	"\n" +
	"\x1csatellite_provisioning.proto\x12\x06hannah\"k\n" +
	"\x19ProvisionSatelliteRequest\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\tR\x04seed\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomIdB=Z;dev.kernstock.net/gessinger/voice/hannah/proxy/proto/hannahb\x06proto3"

var (
	file_satellite_provisioning_proto_rawDescOnce sync.Once
	file_satellite_provisioning_proto_rawDescData []byte
)

func file_satellite_provisioning_proto_rawDescGZIP() []byte {
	file_satellite_provisioning_proto_rawDescOnce.Do(func() {
		file_satellite_provisioning_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_satellite_provisioning_proto_rawDesc), len(file_satellite_provisioning_proto_rawDesc)))
	})
	return file_satellite_provisioning_proto_rawDescData
}

var file_satellite_provisioning_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_satellite_provisioning_proto_goTypes = []any{
	(*ProvisionSatelliteRequest)(nil), // 0: hannah.ProvisionSatelliteRequest
}
var file_satellite_provisioning_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_satellite_provisioning_proto_init() }
func file_satellite_provisioning_proto_init() {
	if File_satellite_provisioning_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_satellite_provisioning_proto_rawDesc), len(file_satellite_provisioning_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_satellite_provisioning_proto_goTypes,
		DependencyIndexes: file_satellite_provisioning_proto_depIdxs,
		MessageInfos:      file_satellite_provisioning_proto_msgTypes,
	}.Build()
	File_satellite_provisioning_proto = out.File
	file_satellite_provisioning_proto_goTypes = nil
	file_satellite_provisioning_proto_depIdxs = nil
}
