// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: satellite_proxy.proto

package hannah

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sent by the proxy periodically to keep the RegisterProxy stream alive.
type ProxyHeartbeat struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ProxyId string                 `protobuf:"bytes,1,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"` // human-readable identifier, e.g. "hannah-proxy-living-room"
	// UDP address the proxy is listening on for satellite connections.
	// When set, Hannah publishes this address to the discovery topic so
	// satellites connect to the proxy instead of Hannah's own UDP server.
	UdpHost       string `protobuf:"bytes,2,opt,name=udp_host,json=udpHost,proto3" json:"udp_host,omitempty"`  // advertise host, e.g. "192.168.8.5"
	UdpPort       int32  `protobuf:"varint,3,opt,name=udp_port,json=udpPort,proto3" json:"udp_port,omitempty"` // UDP port, e.g. 7775
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyHeartbeat) Reset() {
	*x = ProxyHeartbeat{}
	mi := &file_satellite_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyHeartbeat) ProtoMessage() {}

func (x *ProxyHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyHeartbeat.ProtoReflect.Descriptor instead.
func (*ProxyHeartbeat) Descriptor() ([]byte, []int) {
	return file_satellite_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyHeartbeat) GetProxyId() string {
	if x != nil {
		return x.ProxyId
	}
	return ""
}

func (x *ProxyHeartbeat) GetUdpHost() string {
	if x != nil {
		return x.UdpHost
	}
	return ""
}

func (x *ProxyHeartbeat) GetUdpPort() int32 {
	if x != nil {
		return x.UdpPort
	}
	return 0
}

// Sent by Hannah to the proxy over the RegisterProxy stream.
type ProxyCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*ProxyCommand_Ack
	//	*ProxyCommand_PlayAudio
	Command       isProxyCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyCommand) Reset() {
	*x = ProxyCommand{}
	mi := &file_satellite_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyCommand) ProtoMessage() {}

func (x *ProxyCommand) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyCommand.ProtoReflect.Descriptor instead.
func (*ProxyCommand) Descriptor() ([]byte, []int) {
	return file_satellite_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyCommand) GetCommand() isProxyCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ProxyCommand) GetAck() *ProxyAck {
	if x != nil {
		if x, ok := x.Command.(*ProxyCommand_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *ProxyCommand) GetPlayAudio() *PlayAudioCommand {
	if x != nil {
		if x, ok := x.Command.(*ProxyCommand_PlayAudio); ok {
			return x.PlayAudio
		}
	}
	return nil
}

type isProxyCommand_Command interface {
	isProxyCommand_Command()
}

type ProxyCommand_Ack struct {
	Ack *ProxyAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"` // initial confirmation when stream is established
}

type ProxyCommand_PlayAudio struct {
	PlayAudio *PlayAudioCommand `protobuf:"bytes,2,opt,name=play_audio,json=playAudio,proto3,oneof"` // Hannah wants the proxy to play TTS on a satellite
}

func (*ProxyCommand_Ack) isProxyCommand_Command() {}

func (*ProxyCommand_PlayAudio) isProxyCommand_Command() {}

// Sent once by Hannah after RegisterProxy stream is established.
type ProxyAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UdpDisabled   bool                   `protobuf:"varint,1,opt,name=udp_disabled,json=udpDisabled,proto3" json:"udp_disabled,omitempty"` // true = Hannah has disabled its own UDP server
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                             // human-readable status, e.g. "UDP server stopped"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyAck) Reset() {
	*x = ProxyAck{}
	mi := &file_satellite_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyAck) ProtoMessage() {}

func (x *ProxyAck) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyAck.ProtoReflect.Descriptor instead.
func (*ProxyAck) Descriptor() ([]byte, []int) {
	return file_satellite_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *ProxyAck) GetUdpDisabled() bool {
	if x != nil {
		return x.UdpDisabled
	}
	return false
}

func (x *ProxyAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Hannah instructs the proxy to play TTS audio on a specific satellite.
// Used for announcements and other server-initiated audio.
// For streaming: Hannah sends multiple PlayAudioCommands with chunks of PCM.
// is_last=true on the final chunk signals the proxy to send tts_end to the satellite.
type PlayAudioCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`        // satellite device name (as registered via UDP or proxy)
	AudioPcm      []byte                 `protobuf:"bytes,2,opt,name=audio_pcm,json=audioPcm,proto3" json:"audio_pcm,omitempty"`        // raw PCM, 16-bit signed mono
	SampleRate    int32                  `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // e.g. 24000 (Azure) or 16000 (Piper)
	IsLast        bool                   `protobuf:"varint,4,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`             // true on the last chunk of a TTS response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayAudioCommand) Reset() {
	*x = PlayAudioCommand{}
	mi := &file_satellite_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayAudioCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayAudioCommand) ProtoMessage() {}

func (x *PlayAudioCommand) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayAudioCommand.ProtoReflect.Descriptor instead.
func (*PlayAudioCommand) Descriptor() ([]byte, []int) {
	return file_satellite_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *PlayAudioCommand) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PlayAudioCommand) GetAudioPcm() []byte {
	if x != nil {
		return x.AudioPcm
	}
	return nil
}

func (x *PlayAudioCommand) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *PlayAudioCommand) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

// Sent by the proxy when a satellite has finished recording an utterance.
type SubmitSatelliteAudioRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	DeviceId   string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`        // satellite device name
	Room       string                 `protobuf:"bytes,2,opt,name=room,proto3" json:"room,omitempty"`                                // room name (from proxy registration / config)
	AudioPcm   []byte                 `protobuf:"bytes,3,opt,name=audio_pcm,json=audioPcm,proto3" json:"audio_pcm,omitempty"`        // raw PCM, 16-bit signed mono, 16000 Hz
	SampleRate int32                  `protobuf:"varint,4,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // sample rate of the audio (typically 16000)
	// Optional: speaker identity (Hannah users.id) provided by an upstream speaker-ID service.
	// Empty = anonymous (Hannah treats as unknown user).
	SpeakerUserId string `protobuf:"bytes,5,opt,name=speaker_user_id,json=speakerUserId,proto3" json:"speaker_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitSatelliteAudioRequest) Reset() {
	*x = SubmitSatelliteAudioRequest{}
	mi := &file_satellite_proxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitSatelliteAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSatelliteAudioRequest) ProtoMessage() {}

func (x *SubmitSatelliteAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSatelliteAudioRequest.ProtoReflect.Descriptor instead.
func (*SubmitSatelliteAudioRequest) Descriptor() ([]byte, []int) {
	return file_satellite_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *SubmitSatelliteAudioRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SubmitSatelliteAudioRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *SubmitSatelliteAudioRequest) GetAudioPcm() []byte {
	if x != nil {
		return x.AudioPcm
	}
	return nil
}

func (x *SubmitSatelliteAudioRequest) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *SubmitSatelliteAudioRequest) GetSpeakerUserId() string {
	if x != nil {
		return x.SpeakerUserId
	}
	return ""
}

type SubmitSatelliteAudioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transcript    string                 `protobuf:"bytes,1,opt,name=transcript,proto3" json:"transcript,omitempty"`                    // STT result
	Answer        string                 `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`                            // text answer from Hannah
	IntentName    string                 `protobuf:"bytes,3,opt,name=intent_name,json=intentName,proto3" json:"intent_name,omitempty"`  // e.g. "TurnOn", "CarQuery", "Unknown"
	AudioPcm      []byte                 `protobuf:"bytes,4,opt,name=audio_pcm,json=audioPcm,proto3" json:"audio_pcm,omitempty"`        // TTS response as raw PCM, 16-bit signed mono
	SampleRate    int32                  `protobuf:"varint,5,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // sample rate of audio_pcm
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitSatelliteAudioResponse) Reset() {
	*x = SubmitSatelliteAudioResponse{}
	mi := &file_satellite_proxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitSatelliteAudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitSatelliteAudioResponse) ProtoMessage() {}

func (x *SubmitSatelliteAudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitSatelliteAudioResponse.ProtoReflect.Descriptor instead.
func (*SubmitSatelliteAudioResponse) Descriptor() ([]byte, []int) {
	return file_satellite_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *SubmitSatelliteAudioResponse) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *SubmitSatelliteAudioResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *SubmitSatelliteAudioResponse) GetIntentName() string {
	if x != nil {
		return x.IntentName
	}
	return ""
}

func (x *SubmitSatelliteAudioResponse) GetAudioPcm() []byte {
	if x != nil {
		return x.AudioPcm
	}
	return nil
}

func (x *SubmitSatelliteAudioResponse) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

type SatelliteRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // satellite device_id (== eFuse MAC since v0.34), e.g. "e072a1d01adc"
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`                   // IP of the UDP satellite as seen by the proxy, e.g. "192.168.8.42"
	Seed          string                 `protobuf:"bytes,5,opt,name=seed,proto3" json:"seed,omitempty"`                         // one-time pairing token from NVS (empty after successful pairing)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SatelliteRegistration) Reset() {
	*x = SatelliteRegistration{}
	mi := &file_satellite_proxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SatelliteRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatelliteRegistration) ProtoMessage() {}

func (x *SatelliteRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_satellite_proxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatelliteRegistration.ProtoReflect.Descriptor instead.
func (*SatelliteRegistration) Descriptor() ([]byte, []int) {
	return file_satellite_proxy_proto_rawDescGZIP(), []int{6}
}

func (x *SatelliteRegistration) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SatelliteRegistration) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SatelliteRegistration) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

var File_satellite_proxy_proto protoreflect.FileDescriptor

const file_satellite_proxy_proto_rawDesc = "" +
	"\n" +
	"\x15satellite_proxy.proto\x12\x06hannah\"a\n" +
	"\x0eProxyHeartbeat\x12\x19\n" +
	"\bproxy_id\x18\x01 \x01(\tR\aproxyId\x12\x19\n" +
	"\budp_host\x18\x02 \x01(\tR\audpHost\x12\x19\n" +
	"\budp_port\x18\x03 \x01(\x05R\audpPort\"z\n" +
	"\fProxyCommand\x12$\n" +
	"\x03ack\x18\x01 \x01(\v2\x10.hannah.ProxyAckH\x00R\x03ack\x129\n" +
	"\n" +
	"play_audio\x18\x02 \x01(\v2\x18.hannah.PlayAudioCommandH\x00R\tplayAudioB\t\n" +
	"\acommand\"G\n" +
	"\bProxyAck\x12!\n" +
	"\fudp_disabled\x18\x01 \x01(\bR\vudpDisabled\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x86\x01\n" +
	"\x10PlayAudioCommand\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1b\n" +
	"\taudio_pcm\x18\x02 \x01(\fR\baudioPcm\x12\x1f\n" +
	"\vsample_rate\x18\x03 \x01(\x05R\n" +
	"sampleRate\x12\x17\n" +
	"\ais_last\x18\x04 \x01(\bR\x06isLast\"\xb4\x01\n" +
	"\x1bSubmitSatelliteAudioRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04room\x18\x02 \x01(\tR\x04room\x12\x1b\n" +
	"\taudio_pcm\x18\x03 \x01(\fR\baudioPcm\x12\x1f\n" +
	"\vsample_rate\x18\x04 \x01(\x05R\n" +
	"sampleRate\x12&\n" +
	"\x0fspeaker_user_id\x18\x05 \x01(\tR\rspeakerUserId\"\xb5\x01\n" +
	"\x1cSubmitSatelliteAudioResponse\x12\x1e\n" +
	"\n" +
	"transcript\x18\x01 \x01(\tR\n" +
	"transcript\x12\x16\n" +
	"\x06answer\x18\x02 \x01(\tR\x06answer\x12\x1f\n" +
	"\vintent_name\x18\x03 \x01(\tR\n" +
	"intentName\x12\x1b\n" +
	"\taudio_pcm\x18\x04 \x01(\fR\baudioPcm\x12\x1f\n" +
	"\vsample_rate\x18\x05 \x01(\x05R\n" +
	"sampleRate\"|\n" +
	"\x15SatelliteRegistration\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04seed\x18\x05 \x01(\tR\x04seedJ\x04\b\x02\x10\x03J\x04\b\x04\x10\x05R\x04roomR\x06serialB=Z;dev.kernstock.net/gessinger/voice/hannah/proxy/proto/hannahb\x06proto3"

var (
	file_satellite_proxy_proto_rawDescOnce sync.Once
	file_satellite_proxy_proto_rawDescData []byte
)

func file_satellite_proxy_proto_rawDescGZIP() []byte {
	file_satellite_proxy_proto_rawDescOnce.Do(func() {
		file_satellite_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_satellite_proxy_proto_rawDesc), len(file_satellite_proxy_proto_rawDesc)))
	})
	return file_satellite_proxy_proto_rawDescData
}

var file_satellite_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_satellite_proxy_proto_goTypes = []any{
	(*ProxyHeartbeat)(nil),               // 0: hannah.ProxyHeartbeat
	(*ProxyCommand)(nil),                 // 1: hannah.ProxyCommand
	(*ProxyAck)(nil),                     // 2: hannah.ProxyAck
	(*PlayAudioCommand)(nil),             // 3: hannah.PlayAudioCommand
	(*SubmitSatelliteAudioRequest)(nil),  // 4: hannah.SubmitSatelliteAudioRequest
	(*SubmitSatelliteAudioResponse)(nil), // 5: hannah.SubmitSatelliteAudioResponse
	(*SatelliteRegistration)(nil),        // 6: hannah.SatelliteRegistration
}
var file_satellite_proxy_proto_depIdxs = []int32{
	2, // 0: hannah.ProxyCommand.ack:type_name -> hannah.ProxyAck
	3, // 1: hannah.ProxyCommand.play_audio:type_name -> hannah.PlayAudioCommand
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_satellite_proxy_proto_init() }
func file_satellite_proxy_proto_init() {
	if File_satellite_proxy_proto != nil {
		return
	}
	file_satellite_proxy_proto_msgTypes[1].OneofWrappers = []any{
		(*ProxyCommand_Ack)(nil),
		(*ProxyCommand_PlayAudio)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_satellite_proxy_proto_rawDesc), len(file_satellite_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_satellite_proxy_proto_goTypes,
		DependencyIndexes: file_satellite_proxy_proto_depIdxs,
		MessageInfos:      file_satellite_proxy_proto_msgTypes,
	}.Build()
	File_satellite_proxy_proto = out.File
	file_satellite_proxy_proto_goTypes = nil
	file_satellite_proxy_proto_depIdxs = nil
}
