// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: speaker_enrollment.proto

package hannah

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollVoiceprintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`              // Hannah user this voice sample belongs to (users.id, stable)
	AudioPcm      []byte                 `protobuf:"bytes,2,opt,name=audio_pcm,json=audioPcm,proto3" json:"audio_pcm,omitempty"`        // raw PCM, 16-bit signed mono
	SampleRate    int32                  `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"` // e.g. 16000
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollVoiceprintRequest) Reset() {
	*x = EnrollVoiceprintRequest{}
	mi := &file_speaker_enrollment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollVoiceprintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollVoiceprintRequest) ProtoMessage() {}

func (x *EnrollVoiceprintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_speaker_enrollment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollVoiceprintRequest.ProtoReflect.Descriptor instead.
func (*EnrollVoiceprintRequest) Descriptor() ([]byte, []int) {
	return file_speaker_enrollment_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollVoiceprintRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EnrollVoiceprintRequest) GetAudioPcm() []byte {
	if x != nil {
		return x.AudioPcm
	}
	return nil
}

func (x *EnrollVoiceprintRequest) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

var File_speaker_enrollment_proto protoreflect.FileDescriptor

const file_speaker_enrollment_proto_rawDesc = "" +
	"\n" +
	"\x18speaker_enrollment.proto\x12\x06hannah\"p\n" +
	"\x17EnrollVoiceprintRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\taudio_pcm\x18\x02 \x01(\fR\baudioPcm\x12\x1f\n" +
	"\vsample_rate\x18\x03 \x01(\x05R\n" +
	"sampleRateB=Z;dev.kernstock.net/gessinger/voice/hannah/proxy/proto/hannahb\x06proto3"

var (
	file_speaker_enrollment_proto_rawDescOnce sync.Once
	file_speaker_enrollment_proto_rawDescData []byte
)

func file_speaker_enrollment_proto_rawDescGZIP() []byte {
	file_speaker_enrollment_proto_rawDescOnce.Do(func() {
		file_speaker_enrollment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_speaker_enrollment_proto_rawDesc), len(file_speaker_enrollment_proto_rawDesc)))
	})
	return file_speaker_enrollment_proto_rawDescData
}

var file_speaker_enrollment_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_speaker_enrollment_proto_goTypes = []any{
	(*EnrollVoiceprintRequest)(nil), // 0: hannah.EnrollVoiceprintRequest
}
var file_speaker_enrollment_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_speaker_enrollment_proto_init() }
func file_speaker_enrollment_proto_init() {
	if File_speaker_enrollment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_speaker_enrollment_proto_rawDesc), len(file_speaker_enrollment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_speaker_enrollment_proto_goTypes,
		DependencyIndexes: file_speaker_enrollment_proto_depIdxs,
		MessageInfos:      file_speaker_enrollment_proto_msgTypes,
	}.Build()
	File_speaker_enrollment_proto = out.File
	file_speaker_enrollment_proto_goTypes = nil
	file_speaker_enrollment_proto_depIdxs = nil
}
