// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: timer_service.proto

package hannah

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sent by Hannah Core over the TimerConnect stream.
type TimerCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*TimerCommand_Create
	//	*TimerCommand_Cancel
	//	*TimerCommand_List
	//	*TimerCommand_Ready
	//	*TimerCommand_NotReady
	Command       isTimerCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimerCommand) Reset() {
	*x = TimerCommand{}
	mi := &file_timer_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimerCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerCommand) ProtoMessage() {}

func (x *TimerCommand) ProtoReflect() protoreflect.Message {
	mi := &file_timer_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerCommand.ProtoReflect.Descriptor instead.
func (*TimerCommand) Descriptor() ([]byte, []int) {
	return file_timer_service_proto_rawDescGZIP(), []int{0}
}

func (x *TimerCommand) GetCommand() isTimerCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *TimerCommand) GetCreate() *TimerCreate {
	if x != nil {
		if x, ok := x.Command.(*TimerCommand_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *TimerCommand) GetCancel() *TimerCancel {
	if x != nil {
		if x, ok := x.Command.(*TimerCommand_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *TimerCommand) GetList() *TimerListRequest {
	if x != nil {
		if x, ok := x.Command.(*TimerCommand_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *TimerCommand) GetReady() *TimerReady {
	if x != nil {
		if x, ok := x.Command.(*TimerCommand_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *TimerCommand) GetNotReady() *TimerNotReady {
	if x != nil {
		if x, ok := x.Command.(*TimerCommand_NotReady); ok {
			return x.NotReady
		}
	}
	return nil
}

type isTimerCommand_Command interface {
	isTimerCommand_Command()
}

type TimerCommand_Create struct {
	Create *TimerCreate `protobuf:"bytes,1,opt,name=create,proto3,oneof"` // create a new timer
}

type TimerCommand_Cancel struct {
	Cancel *TimerCancel `protobuf:"bytes,2,opt,name=cancel,proto3,oneof"` // cancel an existing timer
}

type TimerCommand_List struct {
	List *TimerListRequest `protobuf:"bytes,3,opt,name=list,proto3,oneof"` // request current timer list
}

type TimerCommand_Ready struct {
	Ready *TimerReady `protobuf:"bytes,4,opt,name=ready,proto3,oneof"` // Hannah is ready to receive pending fired events
}

type TimerCommand_NotReady struct {
	NotReady *TimerNotReady `protobuf:"bytes,5,opt,name=not_ready,json=notReady,proto3,oneof"` // Hannah is temporarily unable to process timer firings
}

func (*TimerCommand_Create) isTimerCommand_Command() {}

func (*TimerCommand_Cancel) isTimerCommand_Command() {}

func (*TimerCommand_List) isTimerCommand_Command() {}

func (*TimerCommand_Ready) isTimerCommand_Command() {}

func (*TimerCommand_NotReady) isTimerCommand_Command() {}

// Hannah signals that she is ready to receive queued TimerFired events.
// Sent after startup once ioBroker states are loaded. The service flushes
// any TimerFired events that occurred while Hannah was offline, in order.
type TimerReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimerReady) Reset() {
	*x = TimerReady{}
	mi := &file_timer_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimerReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerReady) ProtoMessage() {}

func (x *TimerReady) ProtoReflect() protoreflect.Message {
	mi := &file_timer_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerReady.ProtoReflect.Descriptor instead.
func (*TimerReady) Descriptor() ([]byte, []int) {
	return file_timer_service_proto_rawDescGZIP(), []int{1}
}

// Hannah signals a temporary degraded state — the Timer Service should hold
// any TimerFired events in its queue until a subsequent TimerReady is received.
// Hannah sends this when core subsystems are unavailable (e.g. ioBroker disconnected).
type TimerNotReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        *string                `protobuf:"bytes,1,opt,name=reason,proto3,oneof" json:"reason,omitempty"` // human-readable reason, e.g. "ioBroker disconnected"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimerNotReady) Reset() {
	*x = TimerNotReady{}
	mi := &file_timer_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimerNotReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerNotReady) ProtoMessage() {}

func (x *TimerNotReady) ProtoReflect() protoreflect.Message {
	mi := &file_timer_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerNotReady.ProtoReflect.Descriptor instead.
func (*TimerNotReady) Descriptor() ([]byte, []int) {
	return file_timer_service_proto_rawDescGZIP(), []int{2}
}

func (x *TimerNotReady) GetReason() string {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return ""
}

// Hannah instructs the timer service to create a new timer.
type TimerCreate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimerId       string                 `protobuf:"bytes,1,opt,name=timer_id,json=timerId,proto3" json:"timer_id,omitempty"`          // UUID assigned by Hannah
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`                             // human-readable label, e.g. "Spazieren gehen"
	FireAt        int64                  `protobuf:"varint,3,opt,name=fire_at,json=fireAt,proto3" json:"fire_at,omitempty"`            // Unix timestamp (seconds) when to fire
	Room          string                 `protobuf:"bytes,4,opt,name=room,proto3" json:"room,omitempty"`                               // room to announce in, or "all"
	RoomieId      *string                `protobuf:"bytes,5,opt,name=roomie_id,json=roomieId,proto3,oneof" json:"roomie_id,omitempty"` // optional: which user set the timer
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimerCreate) Reset() {
	*x = TimerCreate{}
	mi := &file_timer_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimerCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerCreate) ProtoMessage() {}

func (x *TimerCreate) ProtoReflect() protoreflect.Message {
	mi := &file_timer_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerCreate.ProtoReflect.Descriptor instead.
func (*TimerCreate) Descriptor() ([]byte, []int) {
	return file_timer_service_proto_rawDescGZIP(), []int{3}
}

func (x *TimerCreate) GetTimerId() string {
	if x != nil {
		return x.TimerId
	}
	return ""
}

func (x *TimerCreate) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TimerCreate) GetFireAt() int64 {
	if x != nil {
		return x.FireAt
	}
	return 0
}

func (x *TimerCreate) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *TimerCreate) GetRoomieId() string {
	if x != nil && x.RoomieId != nil {
		return *x.RoomieId
	}
	return ""
}

// Hannah instructs the timer service to cancel a timer.
type TimerCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimerId       string                 `protobuf:"bytes,1,opt,name=timer_id,json=timerId,proto3" json:"timer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimerCancel) Reset() {
	*x = TimerCancel{}
	mi := &file_timer_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimerCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerCancel) ProtoMessage() {}

func (x *TimerCancel) ProtoReflect() protoreflect.Message {
	mi := &file_timer_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerCancel.ProtoReflect.Descriptor instead.
func (*TimerCancel) Descriptor() ([]byte, []int) {
	return file_timer_service_proto_rawDescGZIP(), []int{4}
}

func (x *TimerCancel) GetTimerId() string {
	if x != nil {
		return x.TimerId
	}
	return ""
}

// Hannah requests the current list of active timers (e.g. "welche Timer habe ich?").
type TimerListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimerListRequest) Reset() {
	*x = TimerListRequest{}
	mi := &file_timer_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerListRequest) ProtoMessage() {}

func (x *TimerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_timer_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerListRequest.ProtoReflect.Descriptor instead.
func (*TimerListRequest) Descriptor() ([]byte, []int) {
	return file_timer_service_proto_rawDescGZIP(), []int{5}
}

// Sent by the Timer Service over the TimerConnect stream.
type TimerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*TimerMessage_Ack
	//	*TimerMessage_Fired
	//	*TimerMessage_List
	Payload       isTimerMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimerMessage) Reset() {
	*x = TimerMessage{}
	mi := &file_timer_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerMessage) ProtoMessage() {}

func (x *TimerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_timer_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerMessage.ProtoReflect.Descriptor instead.
func (*TimerMessage) Descriptor() ([]byte, []int) {
	return file_timer_service_proto_rawDescGZIP(), []int{6}
}

func (x *TimerMessage) GetPayload() isTimerMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TimerMessage) GetAck() *TimerAck {
	if x != nil {
		if x, ok := x.Payload.(*TimerMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *TimerMessage) GetFired() *TimerFired {
	if x != nil {
		if x, ok := x.Payload.(*TimerMessage_Fired); ok {
			return x.Fired
		}
	}
	return nil
}

func (x *TimerMessage) GetList() *TimerListResponse {
	if x != nil {
		if x, ok := x.Payload.(*TimerMessage_List); ok {
			return x.List
		}
	}
	return nil
}

type isTimerMessage_Payload interface {
	isTimerMessage_Payload()
}

type TimerMessage_Ack struct {
	Ack *TimerAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"` // initial confirmation when stream is established
}

type TimerMessage_Fired struct {
	Fired *TimerFired `protobuf:"bytes,2,opt,name=fired,proto3,oneof"` // a timer has expired
}

type TimerMessage_List struct {
	List *TimerListResponse `protobuf:"bytes,3,opt,name=list,proto3,oneof"` // response to TimerListRequest
}

func (*TimerMessage_Ack) isTimerMessage_Payload() {}

func (*TimerMessage_Fired) isTimerMessage_Payload() {}

func (*TimerMessage_List) isTimerMessage_Payload() {}

// Sent once by the Timer Service after TimerConnect stream is established.
type TimerAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`                                // human-readable status
	ActiveTimers  int32                  `protobuf:"varint,2,opt,name=active_timers,json=activeTimers,proto3" json:"active_timers,omitempty"` // number of timers currently tracked
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimerAck) Reset() {
	*x = TimerAck{}
	mi := &file_timer_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimerAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerAck) ProtoMessage() {}

func (x *TimerAck) ProtoReflect() protoreflect.Message {
	mi := &file_timer_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerAck.ProtoReflect.Descriptor instead.
func (*TimerAck) Descriptor() ([]byte, []int) {
	return file_timer_service_proto_rawDescGZIP(), []int{7}
}

func (x *TimerAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TimerAck) GetActiveTimers() int32 {
	if x != nil {
		return x.ActiveTimers
	}
	return 0
}

// Timer Service notifies Hannah that a timer has expired.
// Hannah looks up the timer_id in its own store to determine what to announce and where.
type TimerFired struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimerId       string                 `protobuf:"bytes,1,opt,name=timer_id,json=timerId,proto3" json:"timer_id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"` // convenience copy for logging; Hannah has it in its own store
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimerFired) Reset() {
	*x = TimerFired{}
	mi := &file_timer_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimerFired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerFired) ProtoMessage() {}

func (x *TimerFired) ProtoReflect() protoreflect.Message {
	mi := &file_timer_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerFired.ProtoReflect.Descriptor instead.
func (*TimerFired) Descriptor() ([]byte, []int) {
	return file_timer_service_proto_rawDescGZIP(), []int{8}
}

func (x *TimerFired) GetTimerId() string {
	if x != nil {
		return x.TimerId
	}
	return ""
}

func (x *TimerFired) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// Response to TimerListRequest — used for sync and "welche Timer habe ich?" queries.
type TimerListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timers        []*TimerInfo           `protobuf:"bytes,1,rep,name=timers,proto3" json:"timers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimerListResponse) Reset() {
	*x = TimerListResponse{}
	mi := &file_timer_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerListResponse) ProtoMessage() {}

func (x *TimerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_timer_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerListResponse.ProtoReflect.Descriptor instead.
func (*TimerListResponse) Descriptor() ([]byte, []int) {
	return file_timer_service_proto_rawDescGZIP(), []int{9}
}

func (x *TimerListResponse) GetTimers() []*TimerInfo {
	if x != nil {
		return x.Timers
	}
	return nil
}

type TimerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimerId       string                 `protobuf:"bytes,1,opt,name=timer_id,json=timerId,proto3" json:"timer_id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	FireAt        int64                  `protobuf:"varint,3,opt,name=fire_at,json=fireAt,proto3" json:"fire_at,omitempty"` // Unix timestamp (seconds)
	Room          string                 `protobuf:"bytes,4,opt,name=room,proto3" json:"room,omitempty"`
	RoomieId      *string                `protobuf:"bytes,5,opt,name=roomie_id,json=roomieId,proto3,oneof" json:"roomie_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimerInfo) Reset() {
	*x = TimerInfo{}
	mi := &file_timer_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimerInfo) ProtoMessage() {}

func (x *TimerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_timer_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimerInfo.ProtoReflect.Descriptor instead.
func (*TimerInfo) Descriptor() ([]byte, []int) {
	return file_timer_service_proto_rawDescGZIP(), []int{10}
}

func (x *TimerInfo) GetTimerId() string {
	if x != nil {
		return x.TimerId
	}
	return ""
}

func (x *TimerInfo) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TimerInfo) GetFireAt() int64 {
	if x != nil {
		return x.FireAt
	}
	return 0
}

func (x *TimerInfo) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *TimerInfo) GetRoomieId() string {
	if x != nil && x.RoomieId != nil {
		return *x.RoomieId
	}
	return ""
}

var File_timer_service_proto protoreflect.FileDescriptor

const file_timer_service_proto_rawDesc = "" +
	"\n" +
	"\x13timer_service.proto\x12\x06hannah\"\x89\x02\n" +
	"\fTimerCommand\x12-\n" +
	"\x06create\x18\x01 \x01(\v2\x13.hannah.TimerCreateH\x00R\x06create\x12-\n" +
	"\x06cancel\x18\x02 \x01(\v2\x13.hannah.TimerCancelH\x00R\x06cancel\x12.\n" +
	"\x04list\x18\x03 \x01(\v2\x18.hannah.TimerListRequestH\x00R\x04list\x12*\n" +
	"\x05ready\x18\x04 \x01(\v2\x12.hannah.TimerReadyH\x00R\x05ready\x124\n" +
	"\tnot_ready\x18\x05 \x01(\v2\x15.hannah.TimerNotReadyH\x00R\bnotReadyB\t\n" +
	"\acommand\"\f\n" +
	"\n" +
	"TimerReady\"7\n" +
	"\rTimerNotReady\x12\x1b\n" +
	"\x06reason\x18\x01 \x01(\tH\x00R\x06reason\x88\x01\x01B\t\n" +
	"\a_reason\"\x9b\x01\n" +
	"\vTimerCreate\x12\x19\n" +
	"\btimer_id\x18\x01 \x01(\tR\atimerId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x17\n" +
	"\afire_at\x18\x03 \x01(\x03R\x06fireAt\x12\x12\n" +
	"\x04room\x18\x04 \x01(\tR\x04room\x12 \n" +
	"\troomie_id\x18\x05 \x01(\tH\x00R\broomieId\x88\x01\x01B\f\n" +
	"\n" +
	"_roomie_id\"(\n" +
	"\vTimerCancel\x12\x19\n" +
	"\btimer_id\x18\x01 \x01(\tR\atimerId\"\x12\n" +
	"\x10TimerListRequest\"\x9c\x01\n" +
	"\fTimerMessage\x12$\n" +
	"\x03ack\x18\x01 \x01(\v2\x10.hannah.TimerAckH\x00R\x03ack\x12*\n" +
	"\x05fired\x18\x02 \x01(\v2\x12.hannah.TimerFiredH\x00R\x05fired\x12/\n" +
	"\x04list\x18\x03 \x01(\v2\x19.hannah.TimerListResponseH\x00R\x04listB\t\n" +
	"\apayload\"I\n" +
	"\bTimerAck\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12#\n" +
	"\ractive_timers\x18\x02 \x01(\x05R\factiveTimers\"=\n" +
	"\n" +
	"TimerFired\x12\x19\n" +
	"\btimer_id\x18\x01 \x01(\tR\atimerId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\">\n" +
	"\x11TimerListResponse\x12)\n" +
	"\x06timers\x18\x01 \x03(\v2\x11.hannah.TimerInfoR\x06timers\"\x99\x01\n" +
	"\tTimerInfo\x12\x19\n" +
	"\btimer_id\x18\x01 \x01(\tR\atimerId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x17\n" +
	"\afire_at\x18\x03 \x01(\x03R\x06fireAt\x12\x12\n" +
	"\x04room\x18\x04 \x01(\tR\x04room\x12 \n" +
	"\troomie_id\x18\x05 \x01(\tH\x00R\broomieId\x88\x01\x01B\f\n" +
	"\n" +
	"_roomie_idB=Z;dev.kernstock.net/gessinger/voice/hannah/proxy/proto/hannahb\x06proto3"

var (
	file_timer_service_proto_rawDescOnce sync.Once
	file_timer_service_proto_rawDescData []byte
)

func file_timer_service_proto_rawDescGZIP() []byte {
	file_timer_service_proto_rawDescOnce.Do(func() {
		file_timer_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_timer_service_proto_rawDesc), len(file_timer_service_proto_rawDesc)))
	})
	return file_timer_service_proto_rawDescData
}

var file_timer_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_timer_service_proto_goTypes = []any{
	(*TimerCommand)(nil),      // 0: hannah.TimerCommand
	(*TimerReady)(nil),        // 1: hannah.TimerReady
	(*TimerNotReady)(nil),     // 2: hannah.TimerNotReady
	(*TimerCreate)(nil),       // 3: hannah.TimerCreate
	(*TimerCancel)(nil),       // 4: hannah.TimerCancel
	(*TimerListRequest)(nil),  // 5: hannah.TimerListRequest
	(*TimerMessage)(nil),      // 6: hannah.TimerMessage
	(*TimerAck)(nil),          // 7: hannah.TimerAck
	(*TimerFired)(nil),        // 8: hannah.TimerFired
	(*TimerListResponse)(nil), // 9: hannah.TimerListResponse
	(*TimerInfo)(nil),         // 10: hannah.TimerInfo
}
var file_timer_service_proto_depIdxs = []int32{
	3,  // 0: hannah.TimerCommand.create:type_name -> hannah.TimerCreate
	4,  // 1: hannah.TimerCommand.cancel:type_name -> hannah.TimerCancel
	5,  // 2: hannah.TimerCommand.list:type_name -> hannah.TimerListRequest
	1,  // 3: hannah.TimerCommand.ready:type_name -> hannah.TimerReady
	2,  // 4: hannah.TimerCommand.not_ready:type_name -> hannah.TimerNotReady
	7,  // 5: hannah.TimerMessage.ack:type_name -> hannah.TimerAck
	8,  // 6: hannah.TimerMessage.fired:type_name -> hannah.TimerFired
	9,  // 7: hannah.TimerMessage.list:type_name -> hannah.TimerListResponse
	10, // 8: hannah.TimerListResponse.timers:type_name -> hannah.TimerInfo
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_timer_service_proto_init() }
func file_timer_service_proto_init() {
	if File_timer_service_proto != nil {
		return
	}
	file_timer_service_proto_msgTypes[0].OneofWrappers = []any{
		(*TimerCommand_Create)(nil),
		(*TimerCommand_Cancel)(nil),
		(*TimerCommand_List)(nil),
		(*TimerCommand_Ready)(nil),
		(*TimerCommand_NotReady)(nil),
	}
	file_timer_service_proto_msgTypes[2].OneofWrappers = []any{}
	file_timer_service_proto_msgTypes[3].OneofWrappers = []any{}
	file_timer_service_proto_msgTypes[6].OneofWrappers = []any{
		(*TimerMessage_Ack)(nil),
		(*TimerMessage_Fired)(nil),
		(*TimerMessage_List)(nil),
	}
	file_timer_service_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_timer_service_proto_rawDesc), len(file_timer_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_timer_service_proto_goTypes,
		DependencyIndexes: file_timer_service_proto_depIdxs,
		MessageInfos:      file_timer_service_proto_msgTypes,
	}.Build()
	File_timer_service_proto = out.File
	file_timer_service_proto_goTypes = nil
	file_timer_service_proto_depIdxs = nil
}
