// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: user_registry.proto

package hannah

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserName    string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	DisplayName string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	TrustLevel  int32                  `protobuf:"varint,4,opt,name=trust_level,json=trustLevel,proto3" json:"trust_level,omitempty"`
	Active      bool                   `protobuf:"varint,5,opt,name=active,proto3" json:"active,omitempty"`
	// linked_accounts: service → account_id  (e.g. "telegram" → "123456789")
	LinkedAccounts map[string]string `protobuf:"bytes,6,rep,name=linked_accounts,json=linkedAccounts,proto3" json:"linked_accounts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SystemMessages bool              `protobuf:"varint,7,opt,name=system_messages,json=systemMessages,proto3" json:"system_messages,omitempty"` // receives ioBroker/system notifications via Telegram
	Email          string            `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`                                          // #27 Phase 6
	Type           string            `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`                                            // "roomie" | "guest" | "pet", #27 Phase 6
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_registry_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *User) GetTrustLevel() int32 {
	if x != nil {
		return x.TrustLevel
	}
	return 0
}

func (x *User) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *User) GetLinkedAccounts() map[string]string {
	if x != nil {
		return x.LinkedAccounts
	}
	return nil
}

func (x *User) GetSystemMessages() bool {
	if x != nil {
		return x.SystemMessages
	}
	return false
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetUsersRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeInactive bool                   `protobuf:"varint,1,opt,name=include_inactive,json=includeInactive,proto3" json:"include_inactive,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_user_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_registry_proto_rawDescGZIP(), []int{1}
}

func (x *GetUsersRequest) GetIncludeInactive() bool {
	if x != nil {
		return x.IncludeInactive
	}
	return false
}

type GetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResponse) Reset() {
	*x = GetUsersResponse{}
	mi := &file_user_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResponse) ProtoMessage() {}

func (x *GetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResponse.ProtoReflect.Descriptor instead.
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_registry_proto_rawDescGZIP(), []int{2}
}

func (x *GetUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

// Exactly one of the lookup fields should be set.
type GetUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Lookup:
	//
	//	*GetUserRequest_UserName
	//	*GetUserRequest_Id
	//	*GetUserRequest_LinkedAccount
	Lookup isGetUserRequest_Lookup `protobuf_oneof:"lookup"`
	// Only meaningful together with roomie_id: roomie_id alone is not unique across
	// types (a Guest and a Roomie can share a name). Leave UNSPECIFIED if there's no
	// collision; required when one exists, otherwise the RPC fails with
	// FAILED_PRECONDITION naming the colliding types.
	Type          ResidentType `protobuf:"varint,4,opt,name=type,proto3,enum=hannah.ResidentType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_registry_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserRequest) GetLookup() isGetUserRequest_Lookup {
	if x != nil {
		return x.Lookup
	}
	return nil
}

func (x *GetUserRequest) GetUserName() string {
	if x != nil {
		if x, ok := x.Lookup.(*GetUserRequest_UserName); ok {
			return x.UserName
		}
	}
	return ""
}

func (x *GetUserRequest) GetId() int32 {
	if x != nil {
		if x, ok := x.Lookup.(*GetUserRequest_Id); ok {
			return x.Id
		}
	}
	return 0
}

func (x *GetUserRequest) GetLinkedAccount() *LinkedAccountLookup {
	if x != nil {
		if x, ok := x.Lookup.(*GetUserRequest_LinkedAccount); ok {
			return x.LinkedAccount
		}
	}
	return nil
}

func (x *GetUserRequest) GetType() ResidentType {
	if x != nil {
		return x.Type
	}
	return ResidentType_RESIDENT_TYPE_UNSPECIFIED
}

type isGetUserRequest_Lookup interface {
	isGetUserRequest_Lookup()
}

type GetUserRequest_UserName struct {
	UserName string `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3,oneof"`
}

type GetUserRequest_Id struct {
	Id int32 `protobuf:"varint,2,opt,name=id,proto3,oneof"`
}

type GetUserRequest_LinkedAccount struct {
	LinkedAccount *LinkedAccountLookup `protobuf:"bytes,3,opt,name=linked_account,json=linkedAccount,proto3,oneof"`
}

func (*GetUserRequest_UserName) isGetUserRequest_Lookup() {}

func (*GetUserRequest_Id) isGetUserRequest_Lookup() {}

func (*GetUserRequest_LinkedAccount) isGetUserRequest_Lookup() {}

type LinkedAccountLookup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkedAccountLookup) Reset() {
	*x = LinkedAccountLookup{}
	mi := &file_user_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkedAccountLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkedAccountLookup) ProtoMessage() {}

func (x *LinkedAccountLookup) ProtoReflect() protoreflect.Message {
	mi := &file_user_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkedAccountLookup.ProtoReflect.Descriptor instead.
func (*LinkedAccountLookup) Descriptor() ([]byte, []int) {
	return file_user_registry_proto_rawDescGZIP(), []int{4}
}

func (x *LinkedAccountLookup) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LinkedAccountLookup) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"` // only valid when found == true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_user_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_user_registry_proto_rawDescGZIP(), []int{5}
}

func (x *UserResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *UserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_registry_proto_rawDescGZIP(), []int{6}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LinkAccountRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Service         string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	AccountId       string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ProviderPayload string                 `protobuf:"bytes,4,opt,name=provider_payload,json=providerPayload,proto3" json:"provider_payload,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LinkAccountRequest) Reset() {
	*x = LinkAccountRequest{}
	mi := &file_user_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkAccountRequest) ProtoMessage() {}

func (x *LinkAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkAccountRequest.ProtoReflect.Descriptor instead.
func (*LinkAccountRequest) Descriptor() ([]byte, []int) {
	return file_user_registry_proto_rawDescGZIP(), []int{7}
}

func (x *LinkAccountRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LinkAccountRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LinkAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *LinkAccountRequest) GetProviderPayload() string {
	if x != nil {
		return x.ProviderPayload
	}
	return ""
}

type UnlinkAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	RequestorId   int32                  `protobuf:"varint,4,opt,name=requestor_id,json=requestorId,proto3" json:"requestor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkAccountRequest) Reset() {
	*x = UnlinkAccountRequest{}
	mi := &file_user_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkAccountRequest) ProtoMessage() {}

func (x *UnlinkAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkAccountRequest.ProtoReflect.Descriptor instead.
func (*UnlinkAccountRequest) Descriptor() ([]byte, []int) {
	return file_user_registry_proto_rawDescGZIP(), []int{8}
}

func (x *UnlinkAccountRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UnlinkAccountRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *UnlinkAccountRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UnlinkAccountRequest) GetRequestorId() int32 {
	if x != nil {
		return x.RequestorId
	}
	return 0
}

type SetTrustLevelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"` // clamped to [0, 10]
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetTrustLevelRequest) Reset() {
	*x = SetTrustLevelRequest{}
	mi := &file_user_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetTrustLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetTrustLevelRequest) ProtoMessage() {}

func (x *SetTrustLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetTrustLevelRequest.ProtoReflect.Descriptor instead.
func (*SetTrustLevelRequest) Descriptor() ([]byte, []int) {
	return file_user_registry_proto_rawDescGZIP(), []int{9}
}

func (x *SetTrustLevelRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetTrustLevelRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type SetSystemMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Always called by the user for themselves, identified beforehand via a unique
	// linked-account lookup (GetUserRequest.linked_account) — id is already known
	// and unambiguous, unlike roomie_id which can collide across resident types.
	UserId        int32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Enabled       bool  `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSystemMessagesRequest) Reset() {
	*x = SetSystemMessagesRequest{}
	mi := &file_user_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSystemMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSystemMessagesRequest) ProtoMessage() {}

func (x *SetSystemMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSystemMessagesRequest.ProtoReflect.Descriptor instead.
func (*SetSystemMessagesRequest) Descriptor() ([]byte, []int) {
	return file_user_registry_proto_rawDescGZIP(), []int{10}
}

func (x *SetSystemMessagesRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetSystemMessagesRequest) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"` // Klartext, wird serverseitig gehasht — gleicher akzeptierter Constraint wie LoginRequest
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"` // "roomie" | "guest" | "pet"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_registry_proto_rawDescGZIP(), []int{11}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateUserRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Id            int32                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"` // server-assigned, only valid when ok == true
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_user_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_registry_proto_rawDescGZIP(), []int{12}
}

func (x *CreateUserResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CreateUserResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	IsActive      bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Password      string                 `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"` // Klartext, "" = unverändert
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_registry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_registry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_registry_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateUserRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateUserRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateUserRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UpdateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_user_registry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_registry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_user_registry_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteUserRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Resident struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // z.B. "leonie_roomie" — roomie_id + "_" + type
	RoomieId      string                 `protobuf:"bytes,2,opt,name=roomie_id,json=roomieId,proto3" json:"roomie_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // "roomie" | "guest" | "pet"
	Home          bool                   `protobuf:"varint,5,opt,name=home,proto3" json:"home,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resident) Reset() {
	*x = Resident{}
	mi := &file_user_registry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resident) ProtoMessage() {}

func (x *Resident) ProtoReflect() protoreflect.Message {
	mi := &file_user_registry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resident.ProtoReflect.Descriptor instead.
func (*Resident) Descriptor() ([]byte, []int) {
	return file_user_registry_proto_rawDescGZIP(), []int{15}
}

func (x *Resident) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resident) GetRoomieId() string {
	if x != nil {
		return x.RoomieId
	}
	return ""
}

func (x *Resident) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Resident) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resident) GetHome() bool {
	if x != nil {
		return x.Home
	}
	return false
}

type GetResidentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Residents     []*Resident            `protobuf:"bytes,1,rep,name=residents,proto3" json:"residents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResidentsResponse) Reset() {
	*x = GetResidentsResponse{}
	mi := &file_user_registry_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResidentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResidentsResponse) ProtoMessage() {}

func (x *GetResidentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_registry_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResidentsResponse.ProtoReflect.Descriptor instead.
func (*GetResidentsResponse) Descriptor() ([]byte, []int) {
	return file_user_registry_proto_rawDescGZIP(), []int{16}
}

func (x *GetResidentsResponse) GetResidents() []*Resident {
	if x != nil {
		return x.Residents
	}
	return nil
}

var File_user_registry_proto protoreflect.FileDescriptor

const file_user_registry_proto_rawDesc = "" +
	"\n" +
	"\x13user_registry.proto\x12\x06hannah\x1a\vagent.proto\"\xf0\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1f\n" +
	"\vtrust_level\x18\x04 \x01(\x05R\n" +
	"trustLevel\x12\x16\n" +
	"\x06active\x18\x05 \x01(\bR\x06active\x12I\n" +
	"\x0flinked_accounts\x18\x06 \x03(\v2 .hannah.User.LinkedAccountsEntryR\x0elinkedAccounts\x12'\n" +
	"\x0fsystem_messages\x18\a \x01(\bR\x0esystemMessages\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x12\x12\n" +
	"\x04type\x18\t \x01(\tR\x04type\x1aA\n" +
	"\x13LinkedAccountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"<\n" +
	"\x0fGetUsersRequest\x12)\n" +
	"\x10include_inactive\x18\x01 \x01(\bR\x0fincludeInactive\"6\n" +
	"\x10GetUsersResponse\x12\"\n" +
	"\x05users\x18\x01 \x03(\v2\f.hannah.UserR\x05users\"\xbb\x01\n" +
	"\x0eGetUserRequest\x12\x1d\n" +
	"\tuser_name\x18\x01 \x01(\tH\x00R\buserName\x12\x10\n" +
	"\x02id\x18\x02 \x01(\x05H\x00R\x02id\x12D\n" +
	"\x0elinked_account\x18\x03 \x01(\v2\x1b.hannah.LinkedAccountLookupH\x00R\rlinkedAccount\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.hannah.ResidentTypeR\x04typeB\b\n" +
	"\x06lookup\"R\n" +
	"\x13LinkedAccountLookup\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\"F\n" +
	"\fUserResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12 \n" +
	"\x04user\x18\x02 \x01(\v2\f.hannah.UserR\x04user\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x91\x01\n" +
	"\x12LinkAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12)\n" +
	"\x10provider_payload\x18\x04 \x01(\tR\x0fproviderPayload\"\x8b\x01\n" +
	"\x14UnlinkAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12!\n" +
	"\frequestor_id\x18\x04 \x01(\x05R\vrequestorId\"E\n" +
	"\x14SetTrustLevelRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\"M\n" +
	"\x18SetSystemMessagesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\"\x98\x01\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"N\n" +
	"\x12CreateUserResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x05R\x02id\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xb2\x01\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12\x1a\n" +
	"\bpassword\x18\x06 \x01(\tR\bpassword\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"\x82\x01\n" +
	"\bResident\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\troomie_id\x18\x02 \x01(\tR\broomieId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x12\n" +
	"\x04home\x18\x05 \x01(\bR\x04home\"F\n" +
	"\x14GetResidentsResponse\x12.\n" +
	"\tresidents\x18\x01 \x03(\v2\x10.hannah.ResidentR\tresidentsB=Z;dev.kernstock.net/gessinger/voice/hannah/proxy/proto/hannahb\x06proto3"

var (
	file_user_registry_proto_rawDescOnce sync.Once
	file_user_registry_proto_rawDescData []byte
)

func file_user_registry_proto_rawDescGZIP() []byte {
	file_user_registry_proto_rawDescOnce.Do(func() {
		file_user_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_registry_proto_rawDesc), len(file_user_registry_proto_rawDesc)))
	})
	return file_user_registry_proto_rawDescData
}

var file_user_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_user_registry_proto_goTypes = []any{
	(*User)(nil),                     // 0: hannah.User
	(*GetUsersRequest)(nil),          // 1: hannah.GetUsersRequest
	(*GetUsersResponse)(nil),         // 2: hannah.GetUsersResponse
	(*GetUserRequest)(nil),           // 3: hannah.GetUserRequest
	(*LinkedAccountLookup)(nil),      // 4: hannah.LinkedAccountLookup
	(*UserResponse)(nil),             // 5: hannah.UserResponse
	(*LoginRequest)(nil),             // 6: hannah.LoginRequest
	(*LinkAccountRequest)(nil),       // 7: hannah.LinkAccountRequest
	(*UnlinkAccountRequest)(nil),     // 8: hannah.UnlinkAccountRequest
	(*SetTrustLevelRequest)(nil),     // 9: hannah.SetTrustLevelRequest
	(*SetSystemMessagesRequest)(nil), // 10: hannah.SetSystemMessagesRequest
	(*CreateUserRequest)(nil),        // 11: hannah.CreateUserRequest
	(*CreateUserResponse)(nil),       // 12: hannah.CreateUserResponse
	(*UpdateUserRequest)(nil),        // 13: hannah.UpdateUserRequest
	(*DeleteUserRequest)(nil),        // 14: hannah.DeleteUserRequest
	(*Resident)(nil),                 // 15: hannah.Resident
	(*GetResidentsResponse)(nil),     // 16: hannah.GetResidentsResponse
	nil,                              // 17: hannah.User.LinkedAccountsEntry
	(ResidentType)(0),                // 18: hannah.ResidentType
}
var file_user_registry_proto_depIdxs = []int32{
	17, // 0: hannah.User.linked_accounts:type_name -> hannah.User.LinkedAccountsEntry
	0,  // 1: hannah.GetUsersResponse.users:type_name -> hannah.User
	4,  // 2: hannah.GetUserRequest.linked_account:type_name -> hannah.LinkedAccountLookup
	18, // 3: hannah.GetUserRequest.type:type_name -> hannah.ResidentType
	0,  // 4: hannah.UserResponse.user:type_name -> hannah.User
	15, // 5: hannah.GetResidentsResponse.residents:type_name -> hannah.Resident
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_user_registry_proto_init() }
func file_user_registry_proto_init() {
	if File_user_registry_proto != nil {
		return
	}
	file_agent_proto_init()
	file_user_registry_proto_msgTypes[3].OneofWrappers = []any{
		(*GetUserRequest_UserName)(nil),
		(*GetUserRequest_Id)(nil),
		(*GetUserRequest_LinkedAccount)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_registry_proto_rawDesc), len(file_user_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_registry_proto_goTypes,
		DependencyIndexes: file_user_registry_proto_depIdxs,
		MessageInfos:      file_user_registry_proto_msgTypes,
	}.Build()
	File_user_registry_proto = out.File
	file_user_registry_proto_goTypes = nil
	file_user_registry_proto_depIdxs = nil
}
