// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: wakeword_capture.proto

package hannah

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SatelliteCaptureRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	DeviceId string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// "noise" (default) or "hey_hannah" — controls ESP streaming behaviour.
	// noise: continuous auto-flush every 5 s.
	// hey_hannah: stream only while PTT is held, flush on PTT release.
	SampleType    string `protobuf:"bytes,2,opt,name=sample_type,json=sampleType,proto3" json:"sample_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SatelliteCaptureRequest) Reset() {
	*x = SatelliteCaptureRequest{}
	mi := &file_wakeword_capture_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SatelliteCaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatelliteCaptureRequest) ProtoMessage() {}

func (x *SatelliteCaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wakeword_capture_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatelliteCaptureRequest.ProtoReflect.Descriptor instead.
func (*SatelliteCaptureRequest) Descriptor() ([]byte, []int) {
	return file_wakeword_capture_proto_rawDescGZIP(), []int{0}
}

func (x *SatelliteCaptureRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *SatelliteCaptureRequest) GetSampleType() string {
	if x != nil {
		return x.SampleType
	}
	return ""
}

type TriggerPlinkRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceId       string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	RecordDuration float32                `protobuf:"fixed32,2,opt,name=record_duration,json=recordDuration,proto3" json:"record_duration,omitempty"` // seconds to hold virtual PTT after plink (default 3.0)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TriggerPlinkRequest) Reset() {
	*x = TriggerPlinkRequest{}
	mi := &file_wakeword_capture_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerPlinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerPlinkRequest) ProtoMessage() {}

func (x *TriggerPlinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wakeword_capture_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerPlinkRequest.ProtoReflect.Descriptor instead.
func (*TriggerPlinkRequest) Descriptor() ([]byte, []int) {
	return file_wakeword_capture_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerPlinkRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TriggerPlinkRequest) GetRecordDuration() float32 {
	if x != nil {
		return x.RecordDuration
	}
	return 0
}

// ok=false when the satellite is unknown or already captured by another client.
type SatelliteCaptureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SatelliteCaptureResponse) Reset() {
	*x = SatelliteCaptureResponse{}
	mi := &file_wakeword_capture_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SatelliteCaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatelliteCaptureResponse) ProtoMessage() {}

func (x *SatelliteCaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wakeword_capture_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatelliteCaptureResponse.ProtoReflect.Descriptor instead.
func (*SatelliteCaptureResponse) Descriptor() ([]byte, []int) {
	return file_wakeword_capture_proto_rawDescGZIP(), []int{2}
}

func (x *SatelliteCaptureResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SatelliteCaptureResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// A single audio chunk streamed from a captured satellite to the collector.
// end_of_utterance=true marks a PTT-release boundary — the collector should
// finalise and save the accumulated audio as a labelled sample at that point.
type SatelliteAudioChunk struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Pcm            []byte                 `protobuf:"bytes,1,opt,name=pcm,proto3" json:"pcm,omitempty"`                                                // raw PCM, 16-bit signed mono
	SampleRate     int32                  `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`               // Hz, typically 16000
	EndOfUtterance bool                   `protobuf:"varint,3,opt,name=end_of_utterance,json=endOfUtterance,proto3" json:"end_of_utterance,omitempty"` // true = PTT released, utterance boundary
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SatelliteAudioChunk) Reset() {
	*x = SatelliteAudioChunk{}
	mi := &file_wakeword_capture_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SatelliteAudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatelliteAudioChunk) ProtoMessage() {}

func (x *SatelliteAudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_wakeword_capture_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatelliteAudioChunk.ProtoReflect.Descriptor instead.
func (*SatelliteAudioChunk) Descriptor() ([]byte, []int) {
	return file_wakeword_capture_proto_rawDescGZIP(), []int{3}
}

func (x *SatelliteAudioChunk) GetPcm() []byte {
	if x != nil {
		return x.Pcm
	}
	return nil
}

func (x *SatelliteAudioChunk) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *SatelliteAudioChunk) GetEndOfUtterance() bool {
	if x != nil {
		return x.EndOfUtterance
	}
	return false
}

var File_wakeword_capture_proto protoreflect.FileDescriptor

const file_wakeword_capture_proto_rawDesc = "" +
	"\n" +
	"\x16wakeword_capture.proto\x12\x06hannah\"W\n" +
	"\x17SatelliteCaptureRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vsample_type\x18\x02 \x01(\tR\n" +
	"sampleType\"[\n" +
	"\x13TriggerPlinkRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12'\n" +
	"\x0frecord_duration\x18\x02 \x01(\x02R\x0erecordDuration\"@\n" +
	"\x18SatelliteCaptureResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"r\n" +
	"\x13SatelliteAudioChunk\x12\x10\n" +
	"\x03pcm\x18\x01 \x01(\fR\x03pcm\x12\x1f\n" +
	"\vsample_rate\x18\x02 \x01(\x05R\n" +
	"sampleRate\x12(\n" +
	"\x10end_of_utterance\x18\x03 \x01(\bR\x0eendOfUtteranceB=Z;dev.kernstock.net/gessinger/voice/hannah/proxy/proto/hannahb\x06proto3"

var (
	file_wakeword_capture_proto_rawDescOnce sync.Once
	file_wakeword_capture_proto_rawDescData []byte
)

func file_wakeword_capture_proto_rawDescGZIP() []byte {
	file_wakeword_capture_proto_rawDescOnce.Do(func() {
		file_wakeword_capture_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wakeword_capture_proto_rawDesc), len(file_wakeword_capture_proto_rawDesc)))
	})
	return file_wakeword_capture_proto_rawDescData
}

var file_wakeword_capture_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wakeword_capture_proto_goTypes = []any{
	(*SatelliteCaptureRequest)(nil),  // 0: hannah.SatelliteCaptureRequest
	(*TriggerPlinkRequest)(nil),      // 1: hannah.TriggerPlinkRequest
	(*SatelliteCaptureResponse)(nil), // 2: hannah.SatelliteCaptureResponse
	(*SatelliteAudioChunk)(nil),      // 3: hannah.SatelliteAudioChunk
}
var file_wakeword_capture_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wakeword_capture_proto_init() }
func file_wakeword_capture_proto_init() {
	if File_wakeword_capture_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wakeword_capture_proto_rawDesc), len(file_wakeword_capture_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wakeword_capture_proto_goTypes,
		DependencyIndexes: file_wakeword_capture_proto_depIdxs,
		MessageInfos:      file_wakeword_capture_proto_msgTypes,
	}.Build()
	File_wakeword_capture_proto = out.File
	file_wakeword_capture_proto_goTypes = nil
	file_wakeword_capture_proto_depIdxs = nil
}
